* Chapter 19
** Angie
Angie walks Charles and Stephanie in her house. Charles looks aroudn and says, "Nice place" Angie nods and says "thanks I have a few roomates. They're all siblings except two. One is mine sibling and the other is a friend" 

Jessy walks out and says, "Who are they?" Angie replies, "Charles and Stephanie" She looks at them and says, "That's my sister Jessy" Jessy laughs and says, "I know you get into kinky stuff Angie but please don't bring them here" Angie
growls and syas, "Charles might b my dad and I guess you can call Stephanie my step mom if the test come back possitive" Jessy blinks and says, "Damn, So tom realy wasn't your dad." She shrugs and goes into Angie's room.

Charles sighs and says, "Well I'll see you in a couple of days" Angie nods and says, "Yeah" As he's leaving ANgie says, "Hold on" He turns and says, "My whole life I've been calling Tim my dad. I've known he wasn't. For some reason mom never
told me the name of my real dad. She told me what you did. Or well what she wanted me think that you did" Charlest takes a deap breath and says, "    Angie if I knew you existed I would of came by. I saw you mom pregnant a few months later
but she swear it wasn't mine. Now I know." He pats her shoulder and says, "I understand if your going to cry" Angie looking forward says, "First don't touch me. Second I'm not going to cry. This is just alot to take in. I'll get over it or 
I won't" He nods and says, "OK" 

Stephanie laughs and says, "Damn seh sounds like you. You both have that no touching thing" Angie stands up and says, "I came up with that rule becuase o my job. I've had men try to rape me and do other stuff. SO I came up with a no touching
rule. That and I learned advanced selfdefence techniques" Charles nods and says, "I bet that's helped you with your job" Angie nods and says, "It has" 

Charles nods and says, "Well you got my phone number and know where I live come by sometime, and you and your friends drink for free at my pub" Angie nods and says, "Thanks guess I'll give you the same curdicy" 

** Kit

After walking them to their car ANgie walks into Kit's room. Who has her pants around her ancles fingering herslef really into it. ANgie clears her throat and says, "KIt" Kit looks up and says, "YEah?" ANgie replies, "I don't remember you 
being this horny when you first went into heat. What did you take?" Kit shakes her head ands says, "Sorry Angie I'm just so happy your letting me teach you" 

Angie laughs and says, "Of course. Of course. Finally" Kit stops and says, "What?" ANige smiles and says, "I've been such a bad girl, mommy" She crawls towards her and slaps Kit. Kit looks shocked and says, "What the hell ANgie" Angie grins and says
Call me a bad girl and whip me mommy" Kit gets short of breath and says, "What" Angie slaps her again and says, "No" Kit is lost and says, "What is going on". Angie smiles and says, "Don't whip me mommy". Kit shakes her head and sasy, "What the hell
is going on?" 

Angie smiels and says, "Mommy going to whip me" slapping her again. Kit stands up and syas, "Angie did you hit  your head are you ok?" Angie stands up and says, "Kit I think you have ether a domintaion fetish or punishing fetish. I've been
looking for a while trying to find your kink and I got to say. I"m proud of you. Now" ANige takes off her pants pushes KIt on the bed and says, "I'm been a bad girl mommy. I think I need whipped" Kit Angie's naked ass. She feels a excited feeling inside
then does it again. Angie rolls her eyes and says, "Mommy tickles" Kit asks, "I'm afraid of hurting you" Angie laughs and says, "Mommy is' a whimp" Kit again confused says, "Why do you keep calling me mommy?" Angie replies, "It's part of the fetish
it excites you don't it?" Kit don't say anything. But Angie laughs and says, "Come on mommy can't hurt me" Kit does slapps Angie's ass harder. 

Kit's heart starts beating faster. She then does it again, but hears, "Mommy harder" Kit spanks her again harder then harder. Until Angie yells, "Oh that stung mommy" Kit tries to stand up but Angie's across her lap. Angie says, "Kit unless I say pineapple
don't stop. Tha'ts my safe word. So no matter how hard I yell. until I yell pineapple don't stop". Kit feels bad but does as asked.

Harder and harder Kit spanks Angie. Angie's ass shakes with every spanking. Then Kit gigile and says, "Get up"  Kit is loving this. HEr heart is racing and she's geting hornier than she ever has. She reaches into her top dresser drawer and takes out a belt.

Angie looks and says, "Oh no mommy not the belt" Kit quickly puts it away and says, "Oh I'm sorry I got carried away" ANgie groans and says, "Remember the word. you can do anything you want. Unless I say pineapple, don't stop. Do what you like"

Kit takes out the belt. ANgie looks and says, "Please mommy I'm sorry. Kit has her lay down stomach first on the bed and begins whipping ANgie with the belt. 

With every contact the belt makes a loud snapping sound. ANgie flenches and says, "Oh mommy stop" Kit remember and despite guilt does it again and again. Angie scremas, "Mommy this hurts"  Kit's guilt goes away after a minute epecially when she gets tired and takes her drenched
panties off and turns Angie over. Angie loks down and says, "Mommy what are you doing" Kit look mad and says, "Shut up". Angie goes quit and Kit beging licking her pussy. After she's done licking Kit looks up and starting fingering Angie's pussy
then begins licking Angie's clit while fingering her.

After that Kit stands up and says, "Stand up" ANgie lays there" Kit turns her over and slaps her ass and says, "I said get up" Angie stands up and starts ksising kit. "It grabs one of Angie's butt cheaks and spanks her other with her free hand

FInally ANige says, "I'm geting tired sorry Kit, pineapple" Kit smiles and stops. In a excited voice says, "Angie, I'm so" She then covers her face. Angie fench kisses her and says, "It's ok. We all have something. Bondage gets me hot to. I like being the mommy also 
in your fetish. I also like being the teacher or student" Kit looks at her puzzled and says, "What?" Angie smiels and says, "Teacher fetish. SOme people get very hot over it" Kit shrugs and says, "It kind of" she's quit and looks away. Angie kisses her 
and sasy, "Kit it's ok. Plus that might get you more excited that the mommy hting" Kit shakes her head and says, "No my heart is still racing from that".  Angie sighs and says, "Mrs Mathews" Kit laughs and says, "Angie please" Angie shrugs and sasy, "OK. no teacher fetish"

Kit takes the chance and pushes Angie down and says, "young lady" Angie shakes her head and sasy, "Mrs Mathews I'm sorry" Kit then says, "i'll let you off this time, young lady but I'm tired and want to rest" ANgie stndas up and says, "Ok Kit. Come on" 

As they walk into the kitchen. Angie slaps Kit on the ass. Kit jumps and says, "Angie's", iwht a smile. KIt then whispers, "Please Angie keep this a secret" Angie nods and says, "It won't leave the bedroom"

** Jessy

Jessy's laying on the bed listening to her music which is a mix of metal and ninties alternative. Sometimes she strays away to country, but she keeps it a secret that she likes it. Jus tthen she gets a text and sees, "hey" She replies, "Hey Seth"
She's replies with, "How'r u doing today?" Jessy smiles and says, "Great listening to the iron heads" 
He repies, "The metal band?" 
"Yep" 
He then says, "Have you told anyone about us?"
jessy frowns and says, "Nope"
"WHY?"
Jessy groans and sasy, "Because, I don't have a reason. I'm going threw alot. I'm back with my isster. I'm sure I could get Beth to like you but my sister and Kit I don't know"
He replies, "JEssy your acting like I'm a criminal. I'm your boyfriends. we've been dating for three years now. Even when you ran away because of the mess you got yourself in. I'd love to meet you"
Jessy bites her lower lip and says, "I don't know. Talk later"

She puts the phone down beside her and starts imagining everyone geting mad that she's had a boyfriend since she was thirteen. She wants to avoid the talks like do you two sext or have you had sex with him. She don't want to say that
she has sent him some sexy nude image and he sent her a dick pict but she don't want anyone to know.

She decides to go into the kitchen where Kit is sitting odly with a big content smile on her face. She gets a bowl of ceriel kind of disappointed that Kit didn't say hey. But she smiles thinking that them having sex earlier was just that good

After she sits down at the table. Jessy gets another text. She looks and sees, "OK I've been thinking Jessy. My mom knows about you my dad knows about you hell my family knows about you. Why can't we meet. It's been three years I want to know
or we're over. I'm done waisting my time with you" Jessy gets mad and types, "Fuck off" then puts the phone down. She gets a text right back, "Fuck off? I've been patient with you. You've been keeping our relationship secret for years. I'm done"

Jessy growls load and types back, "I know please". she puts the phone down and gets a text right back. Jessy yells, "GOD Shut up!" She looks and sees, "I guess this is it then" Jessy types back, "WHy do you have to do this?" 

She puts the phone down and angie and kit are both looking at her. She smiles inocently and gets up to go to her room but Angie puts a hand on  her shoulder and says, "Is this that gang  you got yourslef messed up with?" Jessy is in the corner
before she could just say, "Nothing" and Angie would ignore it. So she syas, "Mind your own business Angie it's nothign" she  starts to go to her room but Angie says, "No not this time. What is going on?" Jessy is shaking and says, "Oh My GOD!"
agian she tries to leave bu tAngie has firm grasp on her arm. She then also takes her phone.

Jessy reaches for it. Angie sees, "A text app with "Sweety" on top then below it is text. Angie looks at her and says, "What is this?" Jessy mad says, "GIve it back" Angie reads the messages and says, "Finally my little sis has a boyfriend"
 Jessy screams and reaches for it but again Angie manages to keep it away from her. Angie hugs her then says, "HOw long have you been with him? why didn't you say anything? Where does he live?" Jessy blinks shocked and says, "Hwat?"

Angie sits down and types, "This is Jessy's sister. HOw long ahve you two been together?" He repies, "Three year but we just broke up" Angie reads the messages then types, "I'm her sister she told me" Jessy is trying to take the phone back. 
ANgie has about a foot on her so when seh stands up she can easily keep teh phoen waway and says, "Jessy. I've been waiting on  you to get a boyfriend sicne you where nine. Why have you been keeping him a secret. I understand not telling mom. 
but me and dad would liked to know" Jessy finally sits dwon defeated and syas, "Angie, I don't have a reason" finally realising all teh fear she had was nothing. She had a fear and could imagin bad things if she told anyone but now that she is
confrunted she can't htnik of exactly what those would of been. So seh says, "Can I have the phone back?" Angie sighs and says, "He just broke up with you two but I might be able to save it. your lucky you got a sister that has had to weasle
her way out of a few arguemnts"

Angie types, "Your mom becuase she never talked about you or meet you. Well she just told me so that should account for something" He replies, "Proove that your not her acting like someone else sh'se done this before" Angie almost takes a picture of her 
boob but deicdes to type call me at", her number, "I'm sure you've voice chatted with her". He nods and ssays, "No lets video chat" Angie nods and waits for the message. 

She sees a video chat and asnwers it. She smiels at the camera. In front of her is a boy the same age as Jessy maybe a year older. He's grey fox with long hair. wearing a black shirt witha ligtening bolt. 

He blinks and says, "Damn your hot" Kit walks behind him to get something out of the fridge. He says, "Damn she's cute. Jessy is this why you never wanted me to meet them? because there hot as hell and  you where afraid I'd leave  you?"

Jessy is mad but don't answer she then feels a dread coming over her and realises that's what it was. Angie smiles and says, "Oh flattering a kid thinks I'm hot and she's spoken for" He replies, "Just saying she's cute" iwth a smile that is making
jessy jelious a feeling over Kit sh'es not use to. JEssy gets in front of kit and says, "Hey" He smiles nad says, "I'm glad you finally told your hot roomates" Jessy rolls her eys and says, "Can we quit talking about them?" Angie sighs and says,
"Sorry to burst your little teen fantasy there buddy but Kit's spoken for" He replies, "Oh by who?" Angie smiles and says, "ME" then hands the phone to JEsys.

Jessy sighs and says, "There happy?" He replies, "Not really I still haven't met your parents" Angie says, "In her defence mom is a bitch" He shrugs and says, "Well at least we've startde going in the right direction" Angie leans in and whispers,
"Jessy invite him over tonight" She looks up with big scared eyes. Kit smiles thinking it makes JEssy look cute. 

Jessy clears her throat and says, "OK how about we finally meet?" He smiels nad says," Finally. where?" Jessy replies, "Here. We're at One Tenty three, morning grove drive" He writes it down and says, "See you in a few hours" Jessy hangs up and says,"
Damn ANgie I got to get something to wear." Then in a blink she's gone. Angie smiles and says, "Finally I was begining to think she was asexual" Kit takes Angie's hand, weaving her finger between hers. Angie looks shocked and says, "Kit?" Kit smiles 
and says, "Angie we are a couple. You just have some work to do" Angie shrugs and says, "OK" 

Jessy runs out wearing a lacy braw and nothing else and says, "You two need to get something nice on. "Kit wear a long sleeve shirt and that skirt you wear to church the one that goes below your knees" Kit smiles and says, "Trying to make me look
less atractive to him? I kind of liked teh complements" Jessy looks at angie and says, "Angie wear something you'd go see Kit's mom in" Angie shrugs and Kit says, "One thing about dating a girl you can wear each othe'rs cloths come in my room. I'll 
let you wear something.

** Brad
All three are sitting in the living room. Angie says, "This feels weird" Kit rols her eyes and says "Angie sitting with your lets crossed in a skirt is not weird" Angie tugs at her waist and says, "The panties you made me wear" Kit groans and says
Thongs where made so you don't have a panty line. In a skirt it don't matter so you can wear my regular panties" Jessy laughs and says, "Angie your actually wearing panties" Angie skratches at her waist and says, "Yes" 

Just then there's a knock on the door. Jessy's smiles turns to a blank expression with horrified eyes. Angie decides it's best for her to answer the door but Jessy runs to it. She takes two deap breaths beofre opening it. 

He nods and syas, "Hello" then he waives a t acar that leaves. He smiels and says, "My parents won't let me get my license till I get a job" Jessy steps a side nad syas, "Come in" she shuts the door behind him and walks over to the couch wear Kit and Angie where sitting and dtakes seats in two chairs beside it. 
He looks at Angie adn says, "I'm Brad Coddle. You all have a nice house" Angie says, "Thanks, I'm Angie Jessy's sister", points to Kit, "That's Kit" She then syas, "There are three other boys that live here. Mike,  and Chase, Kit's brothers
and Josh, i'm not sure how he ended up here" Brad nods and says, "OK" Jessy smiles and says, "Can I get you something to drink?" Brad shakes his head and says, "No thank you"

They all sit there talking for a while. Brad tells tehm that he's planning on going to college to be a computer programer. Kit nods and syas, "I thought about goign to school to be a artist but now I work at a bookstore" He nods and says, "OK"
Angie smiles and says, "I work with her and I'm part owner of a bar" Jessy rolls her eyes and says, "HE's here to see me can I go to our room? Also can I move into Vicky's old room? Or I can sleep in the basement on a cot" Angie says, "We'll talk
about that later but me and Kit have to go to work anyway. If I find out you did anything" Jessy laughs dna says, "Who are you to say anything" Angie rolls her eyes and says, "IF anything happens Brad I keep condoms in my top drawer. She then leaves
