* Chapter 32

** Angie rides again
Angie looks back at Amber and says, "I forgot something in my dad's office can you let me in?" Amber shrugs and says,
"I don't have access" Angie roles her eyes and says, "Come on"

"I'm leaving Angie"

Angie walks over to her and says, "Amber, lets be straight here something ain't right. Charles is to laxed with stuff
here. I use help run a massive night club that brought in lots of people. We did good because we served everything, 
from good food to good booze. We also had lots of entertainment everynight even tuesday thru thursday the place was 
packed out"

Angie looks down and continues, "The one thing I don't see here that I did there is the numbers. Hell I've been here 
all day and part of last night. There has been at most ten at a time. Those numbers don't add up. No way in Hell, can
this place keep runing like this"

Amber shrugs and says, "I forgot my purse. She reaches in her pocket and pulls out some keys. She opens the door and
walks in. "You followed me in and refused to leave. I left because I trust you. Your his daughter and wanted to know 
more about him, and you thought you would find something in his stuff" 
She then grabs her purse and leaves leaving the door cracked

Angie turns on the light and walks over to his desk. He has a older desktop the kind that uses a out dated operating
system. She turns it on and then types "Charle's_Place" as the password and it lets her in. 

She shakes her head and says, "Come on at least try" she opens up his budgeting app and sees nothing but red. She 
gasps at the numbers and says, "Charles your bankrupt" She looks at his desk and sees it clean then after going threw
some drawers notices alot of  warning letters.

She then hears a deap voice say, "Yes I'm far in the hole. I may have to sell the place. One guy wants to turn it 
into a dive bar where hipsters can drink craft beer while dressed up in ventage clothes. I almost gagged

Angie opens her purse and pulls out a check book. Looks at hte last number and writes down a number double it. She 
tears the check out and says, "Here I'm not asking to buy just buy into it. I want fourty nine percent. It'll still 
be yours but I get a say. THis will put you into the black for a bit and pay off the collectors."

Charles looks at it and says, "Angie this is a big number" Angie frowns and says, "As I told your little playmate. I 
made a good amount of money from my last venture. I want to help. You'll be selling stock in it, but to your daughter" She gets her
purse and leaves before  he can say no.

** Kit's pursuit
Kit is drawing a silly comic about a two cats. Where the male cat tells a bad joke. When Chase walks into her room. 
He shakes his head and says, "At least their not naked on the couch" Kit smiles and starts on another panel. Chase 
again trying to get her attention, says, "You know instead of doing stuff for free you should maybe try selling them" 

Kit looks back at him and says, "I'm just a little mad at you" Chase replies, "Kit, you wanted my opinon I told" Kit 
interrupts him saying, "No... NO! I didn't. I never did. Now I know you think my girlfriend is a nut"

Chase defending himself says, "Kit the girl has almost got you killed. Your drinking now". Looking at her glass of 
whiskey. "Use to be you never did anything worse than soda. Now you do pot, drink and fuck alot of people" 

Kit stands up and slaps him saying, "Chase, what I do is my business. Not yours for your info. Bill kidnapped me,
he would of done that with Angie here or not. Matter of a fact things would of been diferent if she wasn't. I might be
dead or some crack whore because he forced me to take drugs. after he raped me. Or better yet dead because he raped me
to death. 

Stacy, that bitch was just obsessed with Angie. She would of been no matter what.

Chase replies, "What about Julenne and the fact this many people have attacked you is scary" Kit is starting to shake
with anger and says, "Chase, seriosly" She don't have anything else to say. She has been attacked alot and two of the 
three was because of Angie. But none of them was because of her antics. Stacy just got obessed with her. Julienne was
dating Angie till she broke up with her.

Kit kisses Chase on teh lips then smiles. Chase snarls and says, "I'm not Mike, Kit" Kit smiles and grabs his crotch. 

Chase gets angry and knocks her hand away and says, "Kit, see at home  you'd never done this" Kit bows her head nothing
else to say and turns around but says, "Chase at home I was scared. I was scared to death that Bill would get me. He 
was one reason I came here. Here I was free, I was away from him but then he attacked here. Why did he never do it at 
home? It wasn't Angie. It was because there we all protect each other and he knew that. Yes Angie is a whore. I know
What's new. Hell when she was twelve she was fucking Mike. Did you lecture him? Hell Mike was fifteen" 

Chase is the one this time that is speachless. He thinks about kissing Kit but he also knows Kit will call his bluff
and pull him to the bed. So he says, "Kit your a grown woman I hope you know what your doing"

Before leaving she says, "So do you really think I could sell my stuff?" Chase shrugs and says, "I've seen some of 
your stuff I don't jack off to it like Mike but I can see the attraction

** The interview

Vicky and Beth are both dressed in tight fittings dresses Vicky a red dress thinking it'll look good with her red fur. 
Beth is in a black dress, and pearl neckless with large pearls.

When there is a knock on teh door Beth walks up and answers it. A young raccon dressed in a black jeans and a blue 
T-shirt and says, "Hello you look nice" Then smiles at Vicky and nods.

Beth sits him on teh couch while her and Vicky sit in chairs across from him. He sighs and says, "Ok in case you
don't know how this works. We all three go to the hospital and I give the doctor a sample and you get injected with it

Vicky looks at Beth and says, "I thought you said this would be more invulved" The raccoon nods and says, "Well 
because a coworker got a deadly STD we no longer do it like that. Beth says, "I don't want a test tube baby. You can
leave now" He nods and gets up and says, "I can talk to my manager" Vicky calmly says, "Are you conning us? Get out, 
and yes we're calling your manager" 

He quicly says, "OK", then leaves. Beth isn't happy and quickly gets on the computer and gets the number of the place
WHen she calls it she is frustrated with a computer operater and hangs up. 

ONce back inside Beth sits and says, "I need a drink. Vicky please" Vicky shakes her head and says, "This is a good 
test" Beth's hand is shaking and she says, "I really need a drink" Vicky tkaes her and begins making out. But is 
interrupted by a knock on the door.

** Angie goes back
Angie walks back into the bar and says, "Charles can we talk? We need to start making plans to save this place" He
hands back her chekc and says, "Angie I can't take it" Angie looks and sasy, "Go cash it. You have no choice anyway
it's not a gift. I want paid back. What the hell have you given me? A chromesone? 

Charles yawns and says, "Angie, I'll be fine" Angie shakes her head and says, "This place is dead cash the check"

Chalres replies, "Anige I can't take the money" ANgie rpelies,"what are you in debt to the mob also? Cash the fucking
chcek" Charles wants to rip the chck up but instead says, "You win", and leaves.

Angie sits at teh bar and goes into Charle's office after geting Amber to open it. There she starts going threw his
invetory and ordering books.

A hour later he walks back in adn shwos Angie the deposit slip and says, "How am I supose to pay you back?" ANgie
nods and says, "That's what I wanted to talk about. How did you use to make money?" He shrugs and says, "During the
fall football. winter hockey and basketball, spring and summer baseball. People love watching sports at the bar. But 
some fancy sports bar opened in town and now everywone goes there. Leaveing me with my old usuals" 

Angie nods and says, "The biggger cities have something called gaming bars. It's a place where they" Charles stops her
and says, "Hell no I told you I'm not going to run one of those fancy places. I know what those things are and won't 
be having some punk kid that thinks because he can store a thousand points at grand theft mario that somehow he's a 
celebraty and needs free drinks" Angie goes on to her other idea realizing that he has no idea about gaming at all.

Angie says, "OK this are jsut ideas. But another thing we can do is show more than just regular sports. How about
on days that ain't football and stuff we show alternative stuff. Like on mondays and saturdays during the summer. We
play pro wrestling. Also have some nights we play some of the gaming videos. just try diferent stuff until we find 
something people like now.

Charles nods and says, "We can try stuff but I don't like the gaming thing. Still attracts punk kids" Angie
interrupts saying, "Punk kids bring in money. You have to accept some changes. The way your going now is failing"

Charles nods defeated and says, "I know. I"ve been thinking for a while now of adding some gambling machines" Angie
nods and says, "Slot machines yeah that is good. But we need a gambeling license" Charles replies,"I have one I use to 
have a poker night. But people didn't seem to like it but I kept the lesense"

Angie sighs and says, "Well we'll do this later now to get these ideas going"

An hour later Angie closes a notebook and says, "See Charles that was easy" Charles is watching her out of the corner of 
his eyes and says, "I don't like this" Angie sighs then says, "What where you going to do? Just wait till the IRS comes in
and takes everythig and throws you out? Then takes your trailer?"

He goes behind a bar and pulls out a bottle of whiskey and tips the bottle then says, "I didn't have a plan. This has happened
before when people get tired of the fancy places they come back after a few days I'm back in teh black but that has been a few 
years now and people ain't returned"

Angie stands up and says, "Well time to bring them back. See you tomarow start calling some places. I'll" she tears the list 
in half and hands him teh top half, "You call htose I'll call this" He looks at the list and asks, "WHat the hell is it?" Angie 
grins and says, "Investors. Your not selling. I have up percent you can give up ten sell the other 20 to diferent people. Later 
have a board meeting and get this place up again"

He chugs his class and sits down and looks around for Amber. Angie smiels and says, "She left sorry. I'ts after midnight" She 
then takes her leave

** Kit
Kit goes out to get more art supplies and is waiting on teh bus when a young wolf walks up beside her. She smiels at
her and says," Hey" The wolf nods and says, "Hey, your Angie's friend ain't you?" Kit nods and syas, "Yeah, how do you
know her?" The wolf replies, "I use to work with her years ago" Kit nods and says, "That's good" She smiles and says,
"So who is she seeing now?" Kit giggles and says, "Sorta of me" The wolf grins kind of suspicously, then says, "Oh. 
So how long has htis lasted? one or two days?" Kit shrugs and says, "Little over a year but we're childhood friends"

The wolf smiles and says, "that's nice. We kind of dated for a day but then found out she had no intrest in me" Kit 
nods and says, "That sounds like her. W'eer kind of fighting right now but I think it'll work out"

Just then the bus pulls up ending their conversation to Kit's releif. How many people has she dated? It has her 
thinking about what Chase had said. 

Geting home she throws her stuff on her desk and lays down on her bed. Geting her hpone. Chase calling Angie a 
sociopath is still rinigng in her head. She then sends a text to Angie, "We need to talk" She lays the hpone down but 
here's it chime.
SHe picks it up and sees, "Yes we do! I just got you a night job" Kit shocked replies, "WHat? THe hell Angie!!!!"

Angie replies, "Kit this is behind the scenes stuff. You'll be my secreatry. I just boughts a good share of my dad's bar. 
and need somene to do paper work" 

Kit amazed and not knowing what else to say replies, "What about the bookstore? What about Spec? What abotu Cindy?" 

Angie replies, "Kit, NIGHT JOB. This is after we get done there. Trust me this is going to be a hit. Once Charles 
realizes his place is a snore fest and sees the crowds coming in he'll open up to better ideas and I have a bunch.
But talk in a sec. I'm home!!!!!!! :D :D :D"

Kit blinks at the smilies, and says, "When did she use smilies?" Just then ANgie barges in her room adn says, "I feel
great." Kit then realizes Angie has been very depressed and says, "ANgie why haven't you talked to me?" Angie replies, 
"With what Boohooo I lost my job what am I going to do? boohoo. No one wants to hear that shit. stand up I'll share 
some of my ideas. His place is a simple beer joint meaning no stripper poles or that shit. But we need a gimic. Any
ideas your the creative type. What about dress as a cat day. I hear people love dressing as other animals"

Kit not wanting to kill ANgi'es excitment says, "Angie, I don't think your dad will like and aprove to many changes"
ANgie shrugs, "He's not may dad. Dad's stay home and support their kids but Charles is to busy fucking his secertary
he won't care. Hell I can't blame him if I had a hot secetary I'd be fucking her too. That's why I want you there."

Kit sighs and says, "Angie please I don't like paper work" Angie looks at the drawings and said, "All he has is a picture
of those dogs playing pocker. He needs newer stuff maybe you can decerate it" Kit hears Chase telling her to sell her work.
she then smiles and says, "Think I can sell them there?" ANgie shrugs and says, "I don't see why not. But here's the thing.
I'll be spending alot of time there at first. lkie every night so please take this job with me. I really want you to be 
part of this." Kit is speechless. but angie continues, "This is going to be bigger than anything I did before. Because
this one is going to be legal. All legal backers, and no illegal shit at all."

Kit shrugs and says, "Can I at least think about it? I mean I never saw myself as a secertary" ANgie rols her eyes, "Kit
you got a big chest. your sweet you look adorable as hell with you hair pulled back and in dress closes. You have paciounce
of a cat. You can sit on a phone for a hour and not get mad no matter how mad someone on the end is. That one time that guy 
called you by mistake and was angry at his girlfriend you calmed him down and had him talking rationaly, it only took two hours
but you set threw it. I would of told the guy to grow a pair and shut up"

Kit was starting to think she made a mistake beleiving Chase just then remember why she believed him. Stuff like that. She stands up
and says, "Angie please" but don't know what else to say. Angie kisses her and says, "I know I act like a bitch but I've been stressed
my money was runing thin. And couldn't get any call backs. I have years as a barmaid but no one wants to hire me. This is the perfect
opertunity" Kit is haivng mixed feelings about Angie and says, " You have the book store ain't that enough?" ANgie shrugs and syas, 
"Kit I know you like it hell you get to fuck Spec. But really most days I'm fighting sleep, and why the hell does he stil put me in teh stock
room?" Kit replies, "Angie every time your on teh floor he has to deal wtih complaints, and every slow minute your 
hitting on him. I'm geting tired of it I can't imagine him. You've been pestering him for years. just let the man go,
he's not intrested."

Angie winks at her and says, "You would know" Then walks off laughing. Kit is left wondering what she ment and says, "DOes she know
half the stuff she says, don'tmake since?"

** Josh's job
Josh walks into a office building and tells teh security guard, "I'm Josh McPherson, I'm hear for the new sells job"
The guard waves him in after opening the secured door and says, "Mrs. Chantler will be down in a minute. But here is
a temperary pass till you get your real one", handing him a laminated peice of paper with a clip at the end. That he
atatches to the bottom of his shirt.

A middle aged hippo walks up to him she's wearing a brown kaki dress that he can't help but notice barely conceals her
very large chest. She's holding a menalla folder that's filled with papers and says, "Follow me" SHe walks him threw a large lobby with 
a well shined blue lobby floor to the right is a set of wooden double doors with small windows in them. then to the 
left is another set of wooden doors but much fancier. On the door is a small sign that says, "Executive suit"

He's excorted threw a set of glass doors that lead to the stairs and elevators. The elevator has polished red tiles instead of the marble
She presses the up button and says, "While we wait I'll breif you. You'll be answering calls for retail filling orders.

You take their info put it into the database while following a script as close as possible.

The elevator shows up and they get in. The woman presses the second button and says, "I'm Mrs Duddly's secretary" Josh 
nods and sticks his hand out she looks away and says, "I know who you are"

The elevator opens up and they walk into a carpeted lobby then to the left go threw anotehr securied door that opens into a brown carpeted
hall way. TO the left there is a small mail room with a tile floor. That seems to be kept clean but she's walked on down teh hall till she gets to anotehr door
THe hippo pushes hard against it and says, "Push hard or pull up on the bar. SHowing her the bar going up from the door latch.
She's then taken to a cubical and says, "Here you go"

She shows him how to make calls and the script then leaves him. Josh has some trouble at first but after three calls
has it down. After a hour he can resite the script without looking at it.
"Hello Holoared distrubutions. I'm calling for your reorder. Would you like to do that now", He says after calling one
on the list. But is gets, "If I wanted to reorder wouldn't I placed the order. What if I found somoene else" Josh replies,
"We would hate to loose you as a customer and only doing this at your convenious if you would like us to stop all of this
calls just say so" He hears, "Then I said so", and hangs up. Josh then dials the next number. This one thanks him for
calling.

Towards teh end of the day he calls one and hears a sweet voice, "Hello Hollersters Department store" Josh replies, "I'm
Josh McPherson calling" he's interrupted and says, "Josh? are you from Budding holler by any chance?" He replies, "I um."
He was looking forward to geting home and dn't know what to say. The girl says, "I'm Sarah Mathews. Kit's sister" He's 
shocked and says, "Hey Sarah I'm kind of working. Can I finish the call?" She giggles and says, "Yes but can you take down
this number"

He's interrupted by, "Sir please no frantinzing. Mam do you need to make a order?" She replies, "Um NO sorry" They finish the
call and hang up.

Josh takes off the headset and says, "My God I can't do this. He walks over to his supervisor and says, "Sorry my head is killing me
and I swear I killed a bunch of brain cells" She replies ,"Welcome to wrok bud" Jsoh shakes his head and says, "No I'm done" Then leaves.

He's mad that they interrupted his call. There was a coulpe of women in cubicals beside him talking for over a hour just with one
customer. He was told to be polite. But as soon as he gets one thye stop it.

Outside the air is so fresh he takes a deap breath and heads home.
