* Chapter 20
** Kit and Angie at work
Kit stretches and smiles then gets started. Angie smiles at Spec and says, "hellow there" Kit gets mad and slaps ANgie in the back of the head and says, "remember?" Angie rolls her eyes. Spec don't pay any mind to them. The store hasn't
opened yet. So there antict are not his consern. 

Kit points at SPec and sasy, "You need to appolgize", to Angie. Angei rolls her eyes and says, "I thought this was going to only be in the bedroom?" Kit groans and says, "I'm still teaching you manners. We can have fun at night along", She says
it again putting more ethesius on, "Alone" Angie nods and sasy, "What is maddam going to do if I don't" Kit leans in and says, "Please Angie you said you let me do this. So far I'm just thinking of leaving you" Angie laughs and says, "
even after last night?" Kit rolls her eyes and says, "Angie" Angie nods and walks over to Spec and says, "Spec" Spec don't look up and says, "Angie you have a job to do" Angie takes a deap breath then says, "Sorry for hitting on you I
know you have no intrest in me" A sound of a glass breaking comes from teh break room, and Cindy walks out. Angie goes back to Kit. Leaving Spec speachless.

Kit smiles an dsays, "See that wasn't hard. Just don't hit on him or customers" Angie groans and says, "When your looking ok" Kit growls and syas, "No. I mean period" Angie laughs and says, "Kit be careful not to try to change people to much
they may end up resenting you. We've been friends to long and don't want that to happen" Kit frowns and says, "Angie, I'm willing to complemize but didn't you say you have a employee that is always hitting on you, and how annoying she is?"

Angie nods knwoing she was going to bring Jacklyn up. She then laughs and syas, "Damn" she gets her phone out and make a phone call. 

After a second, "Hey Ash, um I have a tiny problem"
She   listens for a second tehn says, "I had to put Jacklyn in lock up last night. I sort of forgot aobut her"
Kit blinks and asks, "You forgot about her? And is locking someone up legal?"

** Vicky and Beth

Vicky sits beside Beth on the couch and says, "So what are we going to do with Jessy's room?" Beth sighs and says, "Her mom made her stay with Her sister and Kit because she's homophobic. Now that Kit and Angie has came out about there 
relationship. She is ether going to force her to come home which won't end good. She'll just find a way to excape. She's a rebel. The other option is she won't care where Jessy lives" 

Vicky frowns and syas, "So I guess the answer is nothing. Thought you where going to make a baby's room out of it. How obsessed you are with one" Beth sighs and says, "I was thining of making my office downstairs"
Vicky blinks and asks, "You have a downstairs?" Beth nods and says, "That door I dind't show when you came in. It goes down to the basement. right now it's got christmas decorations I haven't put them up in five years. But there is also
some clothes I don't wear anymore" Vicky frowns and says, "You could of just said it's where you put the junk you don't use" Beth shrugs and says, "Sure" Vicky smiles and says, "Curiousity has got me. What does it look like?" Beth starts 
to discribe it to her. But Vicky says, "I'd like to see it"

Beth walks her down. Vicky is expecint a small room size place but sees a open floor with four rooms to the back. To the left is two doors one that would b able the size of a bathroom and the other is a bigger room. The floor is covered 
with a thick blue carpet. in the back corner is a old worn leather couch with a thirteen inch CRT TV in front of it on a small table that it fits perfectly on. On both sides of the couch are two end tables one that has a small pedistal
lamp on it. The other a pile of magazine. The rest of the room is filled with junk like Beth discribed

Vicky looks at her and says, "Why do you have that couch over there?" Beth shrugs and says, "I use to have a girlfriend a while back. She was loved to crash here" Vicky asks, "Why ddin't she sleep with you?" Beth replies, "I asked the 
same thing then one day I found out. I had a loud pounding on the door and three cops where at the door. One handed me a peice of paper and asked if someoen lived there. I never heard the name before so I said not. Come to find out she
was robbing gas stations and useing my house as a hide out. She gave me a fake anme and would sleep here for a few days. Before going out and hitting another place" Vicky asks, "Was she on drugs or something?" Beth replies, "No she was
a kleptomaniac. Seh couldn't resist the urge to still things. She would dream about it. Until the urges overwelmed her then she'd go bakc out and do it again. She'd dumb them in a random location and run here to hide." Vicky sighs and
laughs syiang, "Please don't tell me she was a patient of yorus" Beth shakes her head and says, "No we just went on a date. THen she ran to my place out of Breth. I told her I had a old couch downstairs she could sleepon. She said ok. 
I forogt she was down there until one day she walked up and I was masturbating on the living room couch. I screamed and almost called the cops until she reminded me why she was there. we talked and I'm embaresed to say. Had sex. we 
began fucking two days after she staid here. I thought it was odd and figured somethign was up but until that day when the police showed  up. A few minutes later they walked up with her in handcuffes. I was upset that she was lieing to
me. But then she told me everything, as she was saying goodbye.

Vicky shakes her head and says, "Beth, have you had a normal date?" Beth replies, "I have a girlfriend that I fell in love with" Vicky smiles thinking she's talking about her. But hears, "Walked into her place as a suprise once and caught
her in bed with someoen else. I had a short fling with Angie" That one suprises Vicky for a second. Beth continues, "Me and Stephanie got pretty hot for a while" vicky asks, "What happened with her?" Beth shrugs and says, "The relationship 
just went stale. So we decided to call it quits" Vicky nods and says, "I'll I've had is boyfriends before you. The sad thing me and Mike had the closest remantic relationship" Beth smiels and says, "oh how did you meet him?" Vicky blushes
and says, "Beth" She pauses hesitating before, "Mike is my brother" 

To Vicky's amazement Beth nods and says, "Incest. Me and my brother use to sneek around the house until we got caught" Vicky frowns and says, "Does any of your stories end good? It's kind of making me worried about us" Beth smiles and 
says, "I have alot of faith in us. Yes I've had a lot of bad experiances in the past but I've also had allot of good ones. LIke Emily this cute white and black cat that I almost married" Vicky asks, "Why didn't you?" Beth shrugs answers,
"I asked her. She gasped acting all excited. We began planning the wedding until we talked to the wedding planner. Her and the planner started talking and luaghing. Befroe long she started calling her when we where at home. Next thing I
know. She breaks up with me becuase she fell in love with our wedding planner" vicky laughs and says, "That wasn't a happy ending" Beth counters with, "Oh you have some happy ex stories?" vicky thinks then nods and says, "Touche" 

Beth stands up and says, "lets go back upstairs. Vicky looks around and says, "Can we chck the other rooms down here?" Beth shrugs and says, "What? That" points to the first door on the left. The smaller room and says, "Tha'ts a bathroom"
She poitns to the door beside it and says, "Tha'ts a big bedroom. I was going to use as a gym. she then says, "Those four room there are empty rooms I've though of making into bedrooms for the hell of it" 
Vicky replies, "Why so many bedrooms?" Beth says, "I like bedrooms. Also I was thining of making the room to the left a gaming room.  The other rooms will just be random guest rooms  or something. I haven't figured it out. As for the junk
most of it can go in the trash. the other can go in teh building out back that I had built but never used.

** Josh meets someone

Josh walks into the kitchen to get a drink and a bite to eat. When he hears a phone going off he looks and sees Kit's phone on the table.

It rings for a few more minute before stoping. Then right after it start ringing again. Now thinking something maybe wrong he answers it.

"Hello, this is Kit's phone Josh speaking"
A soft voice says, "Hey I  need to talk to Kit"
Josh replies, "Sh eleft her phone here by accedent. You can call Angie. Do you have her number?"
The voice replies, "No I'll just call her back later"
They both say bye then he hangs up.

With that behind him he makes him a sandwhich and a can of soda and goes back to his room. Beforee leaving he looks and sees Kit has a message. Curiousity is geting the best of him but he decides it's best to just leave. But again his mind 
goes back to Kit's phone.

Normally he'd just ignore it but he knows how close Kit is to her sister's and starting to worry. But then remembers she could of just called angie so he lets it go. But then her phone rings. It's from teh same person. Curiousity eating him 
alive knowing that after he told her to call back later, and it's only been a minute he picks up. 

"Hello, Kit's hone"
He's stoped by, "Yeah I know it's Kit's phone this is Josh speaking. I was just bored here and decided to call back"
Josh sits at the table and says, "Here call me at my number because I don't think Kit will like me using her phone". 
He gives her his number then goes to his room. Leaving Kit's phone on the table.

Aftre closing his door his phone rings. With a smile he says, "Hey, Josh's phone Josh speaking" The caller replies, "OK Um you do that every time you answer a call?" Josh replies, "No just trying to be funny. I take from you not laughing
it wasn't" She replies, 'Yeah funny" then trails off. Josh feeling embarresed asks, "So do you have a name or want me to call Kit's caller" She laughs at that one and says, "You can call me Sarah"

