* Chapter 21
** Angie
Angie is sitting at the kitchne table with one leg up on the seat and the other on the floor. Her legs are spread and her panties are on the floor. She's busy sliding her finger in and out of her wet pussy.

Kit walks in and yells, "ANGIE!" Angie looks and says, "Sorry did you want to?" Kit replies, "Angie your at the kitchen table playing with yourself" Angie shrugs and adjust her skirt and says, "No one was home and I was horny. Been alot
lately" Kit roles her eyes and says, "Angie, go to your club and find you a boy if your going in heat" ANgie stands up adn says, "Why there are three able boys here", with a smile. Kit replies,"Mike maybe but he did say for you to leave 
him alone though. Chase I think has a girlfriend. Josh stays to himself. When your walking around in your underwear at night he leaves" Angie smiles and says, "Because he don't want to offend you by taking me on the couch"

Kit frowns and says, "How did you get so arrogent?" Angie replies, "My mom, my aunt, my cousin, my other cousin, where should I start. We all act like this" Kit shakes her ehad and walks to her room adn says, "And how many of them our
married?" Angie replies, "None" Kit conters, "And how many have kids?" Angie replies, softly, "All of them" she then walks after Kit saying, "Not everone can be lucky like you there prissy" Kit looks bakc and says, "IF you want me to fuck
you stop insulting me" Angie replies, "WHen did I say I wanted you" Kit kisses her and says, "I can be hot teacher" Angie laughs and says, "Researching huh?" Kit nods smiling.

Angie french kisses her. Then says, "Can we just rub each other while making out?" Kit kisses her and says, "Where the fun in that" Angie luahgs nad says, "You really like this odn't you?" Kit nods cutely. Angie sighs and says, "I created
a monster" 

THe next thing they're both laying on the bed naked spaking each other while making out. Kit stops Angie begins suck on her kneck saying, "ANgie this is good" ANgie looks up and says, "DO you like the ifnger in you more or the spanking?"
Kit laughs and squeezes Angi'es butt then sliding her middle finger in her ass hole at the same time. Angie maons, "Oh yes I love it in the ass" Kit reaches for her end dable as Angie pulls her left breast and and begins sucking her tit.

Kit moans and says, "Angie I bought something" ANgi elooks up with Kit's nipple still in her mouth and says, "Got any loob?" Kit replies, "WHat" ANgie says, "If your putting that thing in my ass you better have loob." Kit ggigles ain't you 
going to ask what it is?" Angie sucks hard before saying, "A wolf's dick" Kit loving being fingered and her tit sucks says, "It's the same size as Spec's" Angie sits up and says, "Now your just rubbing it in my face" Kit a little hurt 
says, "I was thinking since he won't do anything you could at least have teh next best thing. ANd let me fuck you with it". She turns it on and says, "It's cilicon base dand virbrates" Angie gets up adn says, "So does most dildos I have
four" she then leaves

** Misty
Misty is in her office doing reports when her assistant Mindy runs in adn says, "Misty two men in black coats are asking for you" Misty nods and goes out

She sees two pit bulls in black jackets and black sun glasses looking at her. She knows sh'es in troubel. when she walks up and syas, "Hello there guys" The man on her left says, "We where looking threw your recors and noticed your bank
loan wasn't enought ocover the cost of opening" Misty replies, "I split the left over cost between other epoepl that I signed at part owners." THey pull out a picture and say, "Do you know this man?" Misty feels her stomach churn. She 
sighs and syas, "Whay are you here?" THe man says, "That's Jemremy whinter. He's a wanted loan shark because he gets large loans to people who can't otherwise aford one" Misty shrugs adnd says, "'m good for it" They then show her four
more pictures and say, "Do you know this guys" Misty emptiness grows and says, "Why are you here". The one of the right pulls out handcuffs and syas, "Misty Daffoldil Beaton your underarrest for the murders of Sandy Gallows, Eric minn, Cinthia Glass, and 

Tammy Alst" Misty says, "Can I at least explain?" He says, "You'll have plenty of time with the judge" HE cuffs her then excorts her out. 

At the door she yells, "I have a letter and money in my top drawer" Then the door shuts behind her.

** Angie 
Angie is geting her pussy licked by Kit who's also has the wolf dick shaped dildo up her ass. Kit looks up and syas, "Thanks for not being mad" ANgie says, "Shut up and lick me cunt" ANgie laughs and says, "Damn" Angie laughs and says, 
"Kit I'm starting to miss the shy cute girl that felt bad about having lesbian sex. Kit loks up and says, "I'm happy" 

Angie's phone rings. Angie picks it up. Her good mood fades and says, "I'm on my wayAngie stands up adn says, "KIt get dressed and come with me"

They run to the car and Kit panicked says, "Wha'ts going on" Once in the car Angie says, "Misty was arrested come to find out she was taking hits for a loan shark" Kit asks, "What?" ANgie replies, "KIt you  know a hit man right?" Kit 
replies, "YEs" then suddenly, "MIsty was a hitman?" Angie sighs and says, "She was a while back but stopped when she started bartending and entertaining. SHe said it was more fun. Now she's looking at life with no parol because she 
they said if she shows them where she hd the rest they'll give ehr fifty years" Kit blinks adn says, "That's hwo she attacked Bill so easily" Angie sighs, "I think that's what may of took her back to it. It's not your fault Kit but when
she attacked Bill it reminded her she loves kiling" 

Kit looks at the window and says, "You think you know people" 

They pull up to the club. Ther'es a few other cars parked out front. They run inside jacklyn runs up to her. "I can't believe you locked me up for a day with no food water or anythign" Angie looks at Jacklyn and says, "Shut up now. I 
kept you on because of Misty. Hired you. now she's gone so get the fuck out of here your fired" Jacklyn screams back, "I'm sueing" Kit runs up and syas, "Can she?" Angie shakes her head, and says, "No she's at fault".

They make it to where the other ownsers and partners are they stand beside Beth and Vicky. Then Mindy says, "I'm very sorry to say this. But to MIsty was just arrested adn it looks like she was guilty. She told me a few minutes ago over
the phone she killed to help pay off the bill. She was going to default on it. So he handed her a list of names that had defaulted and said, "I want them dead with proof. Each head is a thousand dollars" She has killed confirmed six they
found two more maby more but she still owe alot of money. the catch for the loan was terrible intrest. Basicly unless she paid thripple the primium every month. it would go up double. So what was a five hundred thousand dollar loan. She 
now owes well over three million. At this rate it'll never be paid off. So unless one of you are millionaires. It sadns me graetly to say this" She cries fro aminute. THey all know what's happening. Even before she says, "As of tonight
the doors to stardust are closed. Good luck.

Angie and the rest mope back to their vehicals for the long ride home.

** Beth and Vicky
Vicky looks over at Beth and says, "What are we going to do? That was out life line" Beth shrugs and says, "I don't know" Vicky replies, "You can go back to the hospital and I can be your cute nurse" Beth replies, "You need a degree to
work there and psychologist don't have nurses. But if you would like to help one. You need a bachelor's degree in psychology. Then take a internship. Next go and get a masters degree. It's not a easy task" Vicky replies, "What are we 
going to do?" Beth shrugs and says, "I don't know honestly. WE all thought Misty had a dark secret but we all thought it was a joke that her dark secret was she was a sexual sadist. Never did any of us imagine she was a killer"

Vicky sighs and says, "So nice Misty that would help anyone else was evil" Beth replies, "I really don't like term but yeah she got pleasure of other's pain. I've been told she would bring male workers into her office late at night 
and torture them. But so many wanted to go in there we thought ti was just a rumor till one boy came out about ready to cry saying MIsty tied him up and started lashing him with a antanna after having him choose a terrible safe word."

Tehy pull into their house and Vicky says, "Before the phone call I was going  to get a shower with you and try to have sex. Now I just want to go to bed. Beth sighs and says, "Yeah I know teh feeling. I wonder hwo Angie is taking this 
she was always close to the girl"

** Mindy

Mindy is in tears as she oepsn the drawer and sees a menala envolope that loks full. Inside is nothing but hundred dollar bills. SHe unfolds the trifolded letter and sees, "Dear Mindy, I'm sorry it had to end like this. But last night
I was sloppy. I think I got everything cleaned up but I might of left a finger print. If I did they'll close on me fast. I left you ten thousand dollars. Take it that money is legal I got it from tips. Don't bother trying to get me freed
I am very guilty. Love Misty"

She refolds the envolope then she notised a key on top another letter. She reads it and all it says, "Your rich", then numbers under it. Curious seh walks to her safe puts the key in and enters the number. 

When it oepns sees ees stacks of cash witha  bullwhipe side it. She looks at it but can't beleive the money the cash is in five hundred dollar bundles stacked ten high and ten wide ten long. She's speechless. 

She calls angie for the hel of it. WHin she answers she don't give Angie a chance to talk she says, "MIsty left me five hundred thousand dollars" She hears, "Damn girl", from Angie

** Angie
"Damn girl", Angie says before ahnging up laughing. Kit looks at her and says, "Agnei why are you laughing. Misty was just arrested fro murder. Your job got closed down. Now all " Angie looks glaces as her and syas, "I have is a book
store job. and plenty if savings. I can live off my saving's fro two years alone" Kit replies, "I"m sorry to ask about your business but how much exactly do you have in there?" Angie smiles and says, "I don't know about sixty three maybe 
sixty six to eighty thousand dollars" Kit looks out her window speechless then says, "You got that legally dind't yoU? " Angie replies, "Yep. One thing I might do is open a small bar use that as a down payment and hire you as my hot
securitary that I fuck on my desk" Kit replies, "I don't work at a strip bar" Angie sighs and says, "Kit honestly I'm geting tired of that. I sort of want to work in a place slower than a big dive bar. Yeah it was the tiem of my life
and helpted me get on my feet when I basicly crashed face first here. But now" She trials off Kit rpelies, "You love showing off your body to screaming men" Angie replies, "It gets old after a while. All of those men want me for sex"

Kit replies, "And you want them for the same thing"

They pull up to there house. After geting out Angie says, "Kit I'm not giving up bar tending but do you really know what the last time I got on stage was?" She shrugs and says, "A week" Angie opens the door  and syas, "A few months befroe 
you came here. I'ts been a really long time. And the strippers just get on my nerves now. Me and Misty did a private show once but even then I just wasn't into it" Kit gives Angie a big hug and says, "Your starting to slow down. She then 
smiles big and french kisses Angie" Angie laughs then says, "And your slowly turning into me. Oh By the way, Doltan told me if the place ever closes you can find him at his apartment. It's in highton Brooks in southpaw" Kit says, "That 
fancy place uptown?" Angie kisses her back and says, "Yep the man maybe way past his prime but he's loaded. He was bragging to me and said he made over ten million when eh was filming and still gets a few hundred thousand every months 
from royalities" Kit laughs as she throws her purse in her room adn says, "IF the man wasn't a morbably obese slob. I'd take him. Hell that dick of his". ANgie laughs and says, "Kit your turning more into me every day"

Kit flips her off and says, "Fuck you Angie", then goes tino her room. ANgie shrugs and says, "My pleasure" Inside Kit says, "I wasn't asking" Angie is undressing and says, "Oh your demanding. ANd Mike is just a little smaller than 

Doltan so if you need a huge cock go to your brother" ANgie looksa t the now naked ANgie and says, "I did last night" 

Angie pushes kis on teh bed reaching up her shirt and taking her panties off. Kit looks down aas Angie start licking and says, "What's going on?" ANgie looks up and syas, "I'm in heat shut up and enjoy" before she starts licking Kit's
wet pussy.
