* Chapter 22
** wrestling
Kit and Angie are watching TV in the basement. There watching wrestling. The peacock is challanging a Rockeweller to the championship when a manager walks and forces a match where he wrestles his partners. 






















Angie shakes her head and says, "I wonder how he's going to get out of this?" Kit looks at her and says, "I love watching it also but you do realise it's fake don't you?" Angie looks at her and says, "Those guys are real athletes I bet
any of those guys can take on a football player and win." Kit laughs and says, "After a two weeks of argueing then you have to order pay per view to see it" Angie turns off the TV because the show is off. She pulls out two tickets and
I was going to take you to see the amtch actually but since you hate it so much fine I'll ask Jacklyn" Kit laughs and syas, "Yeah that will stop the girl from hitting on you. Take her out on a date probably have sex after words. then 
expect her to leave you alone" Angie throws down a ticket and says, "Well if you want to go there. If not go to hell" Kit is smileing and says, "Angie, I told you I'm not going on a date with you until I fill comfortable that your not 
going to imabarese me" Angie turns and says, "It wasn't a date Kit. It was just two friends geting together and having fun. I don't even want you to dress up. Just wear you ammo party shirt" Kit smiles and says, "Why where you going to 
take Jacklyn. Angie replies, "That's the point"

Kit stops her at the top of the stairs and says, "Angie, I was just wondering. How did you afford those tickets? The bar closed down" Angie says, "I have lots in saveing plus I do get paid to work at the book store" Kit replies, "Well
what are you going to do. Your acting like it didn't even effect you. Your best friend was arrested for murder and your businees got closed down because of it" Angie shrugs and says, "So what. Kit when you work in a place like that 
alot of the people you know ain't going to be like they seem. We all knew Misty loved to torture men. She had a usual group that injoyed it. But other times she would trick new guys in for her fun. So killing people for hire ain't reallly
a shock" Kit leaves goes upstaris and says, "Well I'm hurt I really though she was a good person. She came to my rescue when I needed her, and she always helped people out. So I'm a little hurt that she had a drak side"

Angie walks up behind her and says, "Everyone has a dark side Kit. How about you? I mean you have injoy love being spanked and me calling you mommy. Also Iheard you let Josh piss on you" Kit looks and says, "Again go to hell" 

Kit oepsn the door to Mike's room and sees him on the bed geting head from a naked cat. A grey cat with black spots. that is also jacking off his own dick" Kit closes the door slowly adn says, "Ok Mike has a boyfriend now" Angie replies,
"Oh how do you know that?" Kit answers her, "Because Mike is geting a blow job from him" Just then the bed starts squeeking and they hear, "Damn" Kit and Angie leave a little shocked. Kit says, "I thought he was just saying he was gay"
As they make it to the stairs another cat fitting the man's discriptions walks past in a towel. She smiles at Kit and ANgie adn says, "Are you going to join? My brother always says the more the marrier" Angie shrugs and says, "WHy not"
Kit grabs her hand and says, "Because those are two strangres" The cat replies, "Oh you like the girlfriend experiance?" Kit blinks and sasy, "your a whore?" The cat rolls her eyes and says, "Please. Whores are cheap. I prefer to call 
myself a call girl. And my borhter is a escort" Kit wlkas down the staris and ahppily ANigie following. She looks at Angie and sasy, "I think we might need to have a talk with Mike" Angie replies, "Why?" Kit says, "Because he hired two
whores" Angie rolls her eyes says, "There excorts. They cots alot more" Kit confused asks, "Is there a diference?" Angie shrugs and says, "Not really but the more expensive ones hate being called a whore"

Kit sits on teh couch and says, "If people pay you to fuck there is something wrong with you" Angie laughs. Kit looks and sasy< "yes, there is something wrong with you if you fuck for a sandwhich" Angie repleis, "Hey I really love 
sandwhiches"

** Vicky and Beth

Vicky is carrying a box upstaris adn says, "Well this is the last one" Beth walks over and says, Thanks for cleaning out the basement." Vicky whips the sweat off her head and says, "Thanks for helping" Beth replies, "I'm sorry my back was
hurting after cleaning the building and hill off" Vicky shakes her head and says, "Yeah, I loved how you worked. You handed everything to me or pointed" Beth kisses her and says, " And I swear tonight you will love the reward. I have 
something cute I'm going to wear for you" She smiles then runs her hand across Vickly's breast and says, "I have something that your large breast will look good in", smiling. Vicky laughs and says, "I  hope I'm not to sore to injoy it" 

Beth begins looking around and says, "Damn we're out of things to do" Vicky looks at her and says, "WHat now?" Beth looks down and says, "I'm a nervous wreck Vicky. I swore to myself that if for what ever reason I lost my job at the club
I'd open my own place. I'd go back into practice" Vicky smiels big and says, "Your going to open a shrink office?" Beth frowns and says, "Pschologist office, but yeah. come here" She takes Vicky's hand and pulls her to the bedroom where 
Beth opens a trunk and pulls out a rolled up peice of paper. She then takes it to the kitchen table and says, "I've saved up enough money to hire a crew to build me a nice office" She un rolls the paper and shows Vicky the layout.

A while back I got a idea for this and hired a drafter to turn a sketch into a usable blueprint.", Beth says while pointing to a large open room at the front the building. The room makes up at least three quarters of it. then in the back
is two rooms the same size. Beth points to the one on the right and says, "This will be my office and the other is the weighting room. The large room in the front will be a place for kids and adults that just want to come in and relax. 
They won't need a appointment just a place to play video games and watch some tv. Or sit at one of the many couches or chairs and text, read or just mess with thier phones" Vicky asks, "So what if kids and adults start fighting?" Beth 
replies with, "I'll have volunteers. Kids in their junior senior year of high school that needs their volunteer work and/or a job plus I'll have some security" Beth looks over it again and says, "Where are they going to use the restroom?"

Beth looks over the blueprint then says, "Damn it" Vicky laughs and says, "You'd thing the drafter would of pointed that out" Beth replies, "Yeah I'll have to add that. But now that I think of it. I drew this whin I was pretty drunk. Then 
I hired the guy later when I still thought it was a great idea. But now that I think of it. It would never work. No one would want to just come and hang out at a shrink" She sighs and sits down Vicky says, "We'll figure out something" Beth
nods.

** Jessy

Jessy is sitting in her room on the phone, at a desk Angie set up for her to read and play games on her laptop. "Mom really this is just stupid" Her mom replies, "Jessica I don't want you around that" Jessy growls and says, "Mom your a
prejustic bitch you know that?" Her mom infuriated repleis, "Whatch you mouth young lady. You know I can still get teh police there and bring you home?" Jessy growls ands ays, "mom first I'll point out that I've been here with you knoing
and legally sigend release to Angie and Beth allowing me to stay there before you found out she was a lesbian" Her mom replies, "Jessica" Jessy intrupts, "Mom no. I'm bored to death here. Beth always gave me something to do" Her mom 
replies, "Oh my God she had you fuck her?" Jessy geting fed up says, "No she gave me the upstairs and had me to keep it clean. and if I cleaned the rest of the place while she was working she paid me. But if you really want to know. Angie
is gay and we've doing things. Her and Kit fuck all the time. And I joined once hwat do you have to say about that?"

Her mom goes quiet for a minute. Jessy is about to hang up thinking they got disconected when she hears, "Your going down a bad path" Jessy now completely fed up, says, "Mom go to my room and look undre the bed. And look in a red show box
a few minutes later she hears, "My God how did you get this?" Jessy grins and says, "Mom that's you and your girlfriend having sex in the shower. So if your going to chastize anyone whip yourself" She then hangs up.

Jessy hangs up smiling. Her phone starts ringing with out looking she knows it's her mom. She lets it ring for a few times before answering it. Right off she hears, "HOw did you get those" Jessy replies still smiling, "Mom you or what's 
her face is a screamer and was geting pretty loud. I was a sleep and heard maoning, Courus I went in and looked. You where on the floor with your legs up ont eh side of the tub with her on her knees fingering you. I went and got my phone
and began taking pictures. You never even noticed." Her mom furous says, "How often do you walk in" Jessy says, "Mom I heard a loud crash. I ran in to see if you passed out" 

She can hear her mom breathing on the other end clearly mad. Jessy, says, "So what because you want the same thing. As both me and Angie. We're the ones that are bad" HEr mom don't reply. So JEssy says, "What cat got your tounge?" Her mom
then hangs up.

Jessy lays back on the bed laughing. Then after probably fifteen minutes her phone rings again. She picks up frustrated and says, "Mom finally got a come back?" She hears, "Jessy, I can't believe this but mom just did something amazing" 
Jessy laughs and syas, "What would that be. Me and her just had a pretty big fight" "I know she just told me. But soemthing else she said. She told me that she has been fucking her high schol best friend, Daisy" Jessy replies, "Because I
backed her into a corner" Angie sighs and says, "Jessy I've been trying to get threw to her so I dobut you pushing did anything" Jessy replies, "Pictures hcange things, I hapepned to have have some of mom having sex with a white fox named
Daisy" Angie laughs and says, "She brought her to the house? She use to just go out and say her and her friend Daisy where going out for a girls day out. Me and dad new she was probably going and fucking her but he didn't care. But mom 
just called me and told me. But not only did she say she is bisexual herself but she said you can live with Beth if you like. Just stay in contact" Jessy is smiling when Angie says, "I'll call Beth go pack I know you want to go back"

Jessy leaves and Angie makes the call.
