* Chapter 29
** Dr Beth
Beth walks into a hospital. She goes threw the double doors past some floors then up to the front desk. The woman at the desk asks, her if she can do anything. Beth takes a deap breath and says, "Could you call Doctor Stansun and say.
Doctor Livington is here to see him" The woman types on the compuater and says, "I'm sorry doctor but Doctor Stansun left here two years ago"

She sighs disappointed but half expecting something lke this. She says, "Do you know who took his place?" The woman nods and syas, "It seems Doctor Emily did" Beth thinks back but don't remember her. So goes on and says, "Could you see if
she can see me?"

A minute later after talking on the phone she hangs up and tells Beth, "I'm soory but she's in meeting all day. Can I leave a message?" Beth feeling defeated shakes her head and says, "No, but thank you" She turns around wanting a drink and 
walks toward the door.

She almost makes it when she runs into someone. WHo looks and screams, "OH MY GOD!" Beth looksat her and smiles, and says, "Kelly" Kelly nods and hugs her and says, "Beth are you back. Please be back" Beth shrugs and says, "Just visiting
sorry" 

Kelly says, "Well you need to meet Suzy. She took over for Doctor Stansun, I'm sure she'd like to meet you" Kelly leaves and says, "Come on" Beth follows.

A minute later their in the back after going threw some secured doors. 

Kelly knocks on a thick door that has Doctor Suzane Emily on it. Beth says, "She's in a meeting. I don't wont to interrupt" Kelly rolls her eyes and says, "She has meetings on Tuesdays. SHe tells people that don't have a appointment that"

The door opens and a really young deer walks out and smiles at Kelly and says, "Is there anything you need?" Kelly points to Beth and says, "I'd like you to meet the woman that got me to being a assistant. Doctor livington, she likes to be
called Beth though" Beth smiles and says, "Hello doctor" Suzon nods and says, "Call me Suzy. nice to meet you. I was told not to touch your old office so if your hear to come back it just needs dusted" Beth smiels and ays, "Oh no I'm just
here to visit. I had something I needed to ask Jerry" Suzan smiles and says, "Well I took his place so come in" She waves hir in ask me anything. She nods to Kelly and says, "Thank you"

Beth sits across from her and says, "I'm sorry to interrupt" Suzan shakes her head and says, "No it's nothing. Next time just come on back and tell Kelly your hear" Beth sighs and says, "I actually came here for my old job, but I'm to 
nervous and to be honest being back in this area is a bit to much. So I think I'll leave" Suzan nods and says, "How about I don't hire you right back. You come in when you feel like get use to your office and being back befroe we talk about
hiring you again" 

Beth nods and says, "I really didn't expect him to save everything" Suzan replies, "They told me what happened, that must of been horific. If your fear is anyting reminding you of what happened. Everyting was cleaned up"

Beth nods and says, "Ok" Suzan lays some keys on her desk and says, "Go see. If you need me to go with you I can" Beth shakes her head and says, "I can go alone thank you" She picks up the keys then walks out the door.

She walks a little ways downthe hall. Two door down. She stops in front of a light brown door that has a place for a name tag but ntohing. She looks down at her hands and htier shaking hard. Flashes of what happened is popping into her
head. She slowly opens the door before turning on the light to a light beige room. With a Khaki colored carpet. Two black chairs in front of a large oak desk and a leather couch to the right. There is pictures of flowers everywhere. 

The room is scarrier that sshe thought ti would be. And amazing very clean. But then as she walks to her desk she looks at one of th ehcairs and sees a flash of red. She remembers what happened and screams. She runs out of the room fast
slamming the door behind her. 

In the hell she runs into Suzan who hugs her. 

Suzan waves people away and gides Beth into her office and sits her down on the couch and says, "Beth it's OK" Beth is crying histeically" Suzan sits beside her and lets Beth cry on her shoulder. After a few minutes Beth says, "I saw it 
agian. I'm not ready I can't go back" Suzan nods and says, "Beth, I know you want to or you wouldn't but you do need to go at your own pace. The first step is the hardest. You just took it. How about you go home and get a loved one. Your 
boyfriend. Sister somoen that can hold your hand" Beth sighs and says, "I should bring Vicky" Suzan smiles and says, "IS that your sister?" Beth shakes her head and says, "No girlfriend I'm gay" Suzan nods and says, "OK GO get her I'll be 
waiting for you" Beth nods and leaves.

** The pub
Kit walks out of her room wearing a red dress with with shor tsleeves. It glistens because it's cover in glitter. She smiles at ANgie and says, "I've been wanting a reason to wear this" Angie is wearing dark blue jean short shorts and a 
t-shirt. She smiels and says, "Kit you really have never been to one of this have you?" Kit shakes her head and says, "I saw a pub on tv and it was really high class I'm excited" Angie laughs and says, "Your way over dressed. but come on.
ONe question though" Kit nods and says, "Yeah I'll go put someting less formal on" ANgie shakes her head and says, "No you look hot" focussing on how big and formed her breast looks in it. and says, "Are you waring underwear" Kit rols her
eyes and says, "No I'm wearing red underwear" Angie smiles as they walk to her car and says, "Oh that lacy red bra and panties that show your but cheeks?' I love it. SH elooks behind her and sees her tail sticking out the back and says, 
"Damn you make me hard" Kit looks confused and waits by her door, before saying, "I never understood why girls say that. We don't get erections.

Kit was wanting Angie to open the door for her but after Angie gets in Kit opens the door and climbs in. ANgie's car is a small four door car but the back seat is only big enough for small kids. Though one time ANgie and her had sex back
there. They both closed the bookstore. Angie was in heat and Kit was friskey after she gaves Spec head on lunch break. They did it in the back lot of a abandoned grocery store. Kit looks at her and says, "What is there lunch like?" Angie
says, "Kit this isn't a fancy place. Trust me. I don't know wha tshow you saw but tv exagerates. But I'm going to get you that burger" Kit nods and says, "OK"

WHen they pull into a the lot kit is disappointed. Even though Angie told her what to expect she was still expecting a fancy place with a valet and someone to at least seat them.

The walk up to the bar where her actual dad is washing dishes. He looks up and says, "Why hello there ANgie" He looks at Kit and says, "And who is this fancy girl?" Angie nods and says, "Tha'ts Kit you met her" HE smiles and says, "I know
but she wasn't dressed so nice. If she wasn't yours I'd making a move" Kit rolls her eyes and says, "Says well Angie there you go hit onyour dad" Angie shakes her head and says, "No. But I will have a beer and a strawberry daqurery for
Kit also a nice two burger and fries. 

Charles smiles and says, "WE don't mix drinks we have beer, soda and water. We just added liquor last month. Angie rolls her eyes and says, "Charles watch out daiquiris are easy" She walks behind the bar. He steps a side with a smile she
looks under the bar and takes out limes lemons then blends some ice till it's smooth squeezes the lemons and limes into it adds some rum and then strawberries and sugar. Blends it more then pores it into a glass for Kit after wetting the edge so 
salt sticks to hit and gives it to Kit. 

Charles smiles and says, "impressive" Angie rolls her eyes and says, "I didn't even entertain and you thank that's impressive? Charles replies, "YOu know how to do sometign other than serve beer. Yeah that's impressive" Angie sihgs and says,
"I hope your food is good"

Kit loves the drink adn says, "Why have you never made this for me?" Angie responds, "You never asked"  Kit smirks and quitely says, "You never asked" 

Angie grins at Charles and says, "Kit's a bit of a light weight" He nods and says, "And you put a extra shot in that" Angie shrugs then says, "Hey you should see her when she's stoned. She's fuck a curl...." Kit jumps up
and covers Angie's mouth cutting her off. Kit embarresed says, "I caught her doing a rock once" Charles shakes as their food is brought out. By a slim weasle who pulls out her book and says, "Anything else" Charles looks at her and says, 
Sabrina, this here is my daughter" pointing to Angie. THe weasle nods and puts the book back up and says, "Nice to meet you mam"

Kit takes a bite of the food and says, "Oh my this is good" She eats it real fast forgeting about manners. Angie laughs and says, "Here I thought you where begining to handle liquor better" Kit licks her fingers and says, "That was good 
what's fro desert" 

Charles shrugs and says, "Most just have a cold beer" Kit smiles and notices Charles is moving a bit. She looks at her class and sees it empty and aksed for another. Angie looks at Charles who says, "I have a policy if you get drunk off
the first glass. He waves it off and says, "Fuck it. I don't I just never saw anyone get drunk off the first glass"

Angie says, "Well Charle I may of slipped her five shots. But I'm driving" He takes her beer and syas, "I just got to know you Angie" She takes it back and says, "It'll take about five of those to get me drunk" He shakes his head and says
"So hwo's everything been?" Angie replies while eating a fry, "Well I'm thinking of opening my own place as I told you. But still haven't found any backers" Kit blurts out, "She ain't looked" Angie shoves her gently. But Kit falls off her 
stool.

Charles looks at Kit and says, "I never thought I'd have to draw the cut off on the first glass but she's drunk" Kit sits back on the stool staggering a little. Angie laughs and says, "Girl I'm going to have to get you drunk more often. 
But I don't remembre you ever geting like this" Kit whispers, "I'm acting trying to rempress your dad" Angie says, "I think you mean inpress and your drunk honey. Anyway he's already proud of me" He just stands smiling. Kit whispers, "I
think he's cute" Angie takes the empty glass and says, "She'll have a black coffee, and you may have beer goggles" Charles laughing says, "Sure will. But I was kind of wonder hwo drunk she would get off of two glasses"

He slides a cup to Kit who starts drinking it. HE looks and says, "That's very hot honey" Kit looks pained and says, "But good" Angie laughs and says, "I probably should get her home" Charles nods and says, "How about you come by tonight
and make a few bucks? I'm sure my nine o'clock crowed would love some mixed drinks. Maybe you can show me that bottle flipping they do in the fancy places" Angie nods and says, "OK Go get about six bottle of the cheapest liquor you can 
find"

Curious he asks, "Why cheapest" Angie replies, "Because your going to drop them. But I might take you up on the offer. If not youtube is a thing" She takes Kit by the arm and leads her out.

Kit leans in and says, "I wonder what he looks like naked" Angie ignores the comment and leaves. Charles laughs and picks up their dirty dishes.
