* Chapter 26
** Angie and Kit
Angie sits down on the couch with Kit and says, "First thing I don't want a big hug and saying this is a break threw" 

Kit smiles waiting on something good. 

Angie sighs and says, "Promise" Kit is giddy adn nods. Angie knows at any minute she'll break but says, "I went to my usual sandwhich shop today and got my usual sandwhich" Kit nods 

Angie continues, "The woman taking my order offered me a alternative way to pay. I didn't take it" 

Kit nods and says, "Angie why would I get giddy over this?"

Angie shrugs and says, "because before you I would of took her in the back and fucked her brains out. Instead I just kept hearing your voice"

Kit smiles and says, "But you have a long way to go. But now what do you wantme to do to you?" Angie shrugs

Angie says, "For one is be happy for me."

"How is not being a slut a big thing? I'd bet my pay check that you won't last a week"

Angie nods then says, "OK" Kit crosses her arms and replies, "First also I'd like to see this sandwhich place"

Angie shrugs and says, "OK" She grabs her jacket and says, "OK" 

Kit smiles and follows

** Badger trouble
As their going to the sadnwhich shop. Kit looks into the book store as they pass it. Kit laughs and says, "Damn looks like Spec is having a good time talking to that badger"

Angie looks at her fast and asks, "What?" Kit repeats herself. Angie, spins the wheel of her car to do a quick tight u-turn that throws Kit against the door. The park in front of the store.  She runs
out of the car and towards the store.

Kit gets out yelling ,"WHAT?!" Inside Angie says, "Why are you hear?" Spec is laughing. Then the badger turns and says, "Oh my god it's you bitch. First you get me fired now your trying to get me thown out of a store
well how about this. Why can't you laeve your a customer like me" Spec is mad and says, "Angie you can't just come in here and throw out customers. Your not working right now it's time to leave. Anyway I decide who gets thrown out"

The badger smirks and syas, "Well well well. Looks like it's time for a bit of pay back" 

Spec confused says, "What?" The badger turns and says, "Thsi little worker here was at my last job. And struck me. Yeah and then she got me fired. I just asked her if she would like a drink with her sandwhich. She called me a whore and 
got me fired".

Angie gets mad and says, "You lieing bitch!" Angie gets mad and says, "Angie it's time to leave." The badger smirks and says, "Don't feel good does it whore?" Angie growls and says, "See you tomarow Spec" Spec nods and says, "OK"

Angie gets in and slams the door. Kit who just walked in the store followed her out sits down adn says, "What the hellw as all that?" Angie growls and replies," KIt that bitch called me a whore " Confused Kit says, "Angie you are a
whore and you use to be proud of it. Angie starts the car staring off into space, "Kit, that's the situation I was talking about. I kept hearing you. So I couldn't hell the cock sucker even has a nice chest.

Kit pats Angie's shoulder and says, "Angie" Angie pushes her hand away and says, "Unless your going to say go kick that sluts ass. Shut up" Kit sits up straight"

** Jessy's problem
Beth walks into the living room. Jessy is at the themistat in front of the stairs. Beth walks up and says, "Hey buddy" Jessy growls and says, "Hey Beth" Beth puts a hand on her and says, "Oh someone's hot" Jessy sighs and says, "Yes,
you caught me I'm in heat" Beth giggles and says, "It's ok your just turning into a woman. This happens to all of us" Jessy turns to go back up to the rooma dn says, "Beth I had the talk in tschool when I was twelve." Beth smiles and says,
"Jessy I'm new to this" Jessy replies, "Beth your wanting to be a mom. Your going to have the chance to give the talk. Hell both you and Vicky are planning on geting nocked up. You might have two girls or one boy and a girl or" Beth puts 
her hand up and syas, "I got it" Jessy goes on.

She walks flops down on teh couch outside her room and turns the tv on. 

"Damn I wish I had a boyfriend. Or a girlfriend"

Next she smiles and says, "but I do have a couple of friends that I have had sex with"

She wlaks odnwstairs and finds Beth.

She's in teh kitchen hidding bhind a cabinet door.

"Hey Beth"

Beth closes the door fast and says, "Hey Jess want to talk" Jessica rolls her eyes and replies, "Beth I don't care you where geting a drink. But seriously if you rgoing to get pregnant your going to need to quit"

Beth acting inoscent says, "I don't know what your talking about", as she's stnaidng up. Jessy walks over to the cabinet Beth was just standing at. Opens it and takes out a bottle of rum.

After taking a swig. Beth gasps and syas, "Your underage" Jessica shrugs and says, "you where supose to quit"

I'm having a relapse"

"you never stopped"

"Did not"

Jessy smiels and walks over to the sink opens it and reaches in teh back and begins taking out bottles of whiskey and other liquors.

Beth starts taking them and syas, "How did you find those" Jessy smiles and says, "You need a better hidding spot also. Your kids will find your hidding spots in minutes. It took me three" 

"I thought that was Vicky drinking that"

Jessy shrugs and says, "It was I had to act like I was geting milk. After I found out that comes out of a cows tits I really stoped drinking it so much that and after I saw a vidiow of a cow with G cup boobs squirting milk out into 
the mouthes of three wolves jcaking off to it" Again Beth gasps and says, "You got pass my filters" Jessy leans in and says, "Cute pussy, isn't a good password. It was the first password I tried"

Beth looks down and says, "I'll rehide my liquor to a harder spot but how did you know I was drinking?" Jessy laughs, "Don't hide it in the gurage that's the next place I was going to look" Beth smiels and opens her mouth. Jessy says, 
"Don't hide it in the same spot just moved in a diferent spot" Beth smiels and opens her mouth again. Jessy shakes her head before saying, "Don't hide it in the bedroom. Vicky will find it"

Just then they hear, "Find what?" Beth quickly puts the bottle up and says, "Nothing she'll find your suprize" Vicky opens the cabinetes and starts pulling the bottles out. 

"Beth I know you have this. But I thought you where going to quit"

Beth looks down and syas, "I'm cutting down" Vicky kisses her and says, "I know"

Jessy says, "You two I have a problem" Beth covers her mouth and runs and hugs Jessy saying, "We'll quit together" Jessy backs up and says, "No I"m in heat and hrony. Could one of you hep a girl out?"

Beth covers her mouth and syas, "I can't do that with a minor" Jessy rolls her eyes repling, "I'm sixteen. I'm legally aloud to concent to sex. Also are you drunk?" 

Beth laeves saying, "No I only had one glass"

Vicky sighs and syas, "Jessy, yes she's drunk. And second go finger yourself like me and Kit had to"  Jessy laughs and says, "OH Angie told me about you and Mike. Don't forget Donny" Vicky turns and says, "Donny?"

Jessy smiles saying, "That cute beaver that use to live on the other side of town. That you use to snick in your room" 

Vicky blushes and leaves.

Jessy laughs and pulls out a bottle and takes a swig. SHe hears, "Me and Donny only did it three times. WE then where caught" Jessy turns around with the bottle in her hand. 

Vicky has her arms crossed and says, "LIke you" Points, "NOw put the bottle up. I'm helping Beth hide htem" Jesy rolls her eyes and hand the bottle to Vicky before leaving.

** Mike's date
Mike walks out of Ashley's apartment with her. She's a blond fox he thinks is cute. At his car after leting her in and geting in himself. HE says, "So I was planning on going to see that new space movie" She grins and replies, "That 
sound nice but I'd rather go see flowers in the wind" Mike smiles but feels dreading having to go see a chick flick. He also knows she's testing him. At least he hopes.
 
later as their walksing out Mike has a sleeping look on his face and says, "Sorry I fell a sleep." Ashley shrugs and syas, "The only part I dind't like was when the usher woke up up becuas eyou where snoring" Mike replies, "Agian I'm 
sorry" She shrugs and says, "Just take me home" Mike repeats, "I'm sorry" not sure why she's so torn up on him falling a sleep. But not oging to ask" Instead he asks, "Could we at least go to get something to eat? I have a reservation"

Ashley shrugs and says, "Sure" Mike is feeling that besides her cuteness the onlything she has going for her is her cuteness. 

Then when their going to the place she sits texting on her phone. He's thinking of just taking her home and taking Kit or his brother to dinner. But then after their inside she looks around and says, "You really put some money into this"

Mike shrugs and says, "I actually know the owner so he gives me a discount", he's finguring he won't ask her out on the another date. But she smiles and says, "Sorry about geting so mad" Mike nods and says, "Again sorry about falling a 
sleep" Ashley sighs and says, "You probably think I'm a bitch don't you"

In his head he says, "Yep" but says, "No" She bows her head and says, "I was thinking in the car. I'm sure you dind't mean to put your face on my hcest" Mike coughs shocked, he was trying to be a gentalmen but instead wasn't. So he says,
"Ashley I'm so sorry." She shakes her head and replies, "I loved the move but it's also the fifth time I've seen it. I've dated three men bfore you  and they fell a sleep. Also every man in there but this gay couple was a sleep. And one of 
them was snoring louder than you" Miek laughs and says, "Must b a man thing" 

She looks over the menu and says, "About a quarter of the woman was a sleep also. I don't knwo what is so boring about a young girl going  out on her own and findign herslef. Then realsling the whild floowers she use to watch float past
her windwo when the wind blew was what truely made her happy. So she decided to restore a house near her old place. But then she was dianosed with cancer. But at the end as she was dieing of the desease she watched the flowers float past
her window as she took her last breath"

She whipes the tears from her eys and says, "It's so beatiful" Mike nods and sas, "I see it now" She perks up and says, "So can we go see it again this weekend?" Mike sighs and syas, "Sure" praying she is just testing him.
