* Kit's christmas
Angie and Kit are cuddled on the couch under a knitted red blanket. Kit smiles and says, "Your right having sex on the couch when everyone's home is exciteing" Angie looks down and kisses her and takes teh ahcnace to rub Kit's naked pussy.
Kit giglges and says, "Angie" Angie squeezes Kit's chest and says, "What?" 

Kit stands up adn gathers her clothes. Angie bends over and looks at Kit's pussy and says, "DId you like sleeping naked in hear?" Kit has a blacklacy braw and matching panties. That's obaque on the front but around the edges it's lacy but
see threw.

Angie likes her lips and says, "That pussy was good also" Kit then gets excited and sits down on the couch and saysm, "Oh I was thinking. What do you want for chrismtas? I don't know what to buy a slut" She ends with a smile.

Angie shrugs and says, "My Dildo is geting kind of old" Kit gets teh sarcasm and says, "Sorry, you  know my family always make a big deal out of this and for the last couple of years the only way I get to celebrate is watching old
christmas shows on local tv because your to cheap to get satalite even though your loaded" 

Angie stands up and fluffs her boob in hopes of geting Kit turned on again but Kit is already dressed and goign to her room

Frustrated Angie says, "Damn might as well get dressed also" SHe then yells out, "Kit are you running to work or want me to take you?" Kit replies, "When the hell did I start running?" Angie laughs and says, "That day I left pissed off"
Kit yells back, "Fuck you!" ANgie laughs and walks into Kit's room dressed and says, "OH you want me a fourth time?" Kit shakes her head and says, "We have thirty minutes till work" Angie smiles and says, "I can make you come in five. 
So lets go? I'm pretty horny. That black bra of yours gets me going" Kit fixes her shirt and says, "Lets go"

After puting her purse up in the employee area Kit walks to the register and helps a customer. She smiles after taking his money and putting his book in a bag and says, "Merry Christmas" The woman rols her eyes. Kit helps a few more 
people and after putting their stuff away she gives them a chearful smiles and says, "Merry Christmas" most smiles back and says, "Merry Christmas to you also" One flipped her off. Otheeer's just wave and walk out. 

Aftre a bit Kit smiles at Angie adn says, "Angie I need to pee can you take over for me?" Angie grins and says, "I wish I could watch you pee but yeah I'll take over" Kit shakes her head and says, "OK I'll be fast ,Josh"

Spec walks past Angie smiels and says, "How about I help you?" Spec replies, "I'm your boss, Angie" Angie grins and says, "I've been bad want to spank me boss?" Spec replies, "No but I can fire you" Ange grins and says, "Sounds kinky"
Then a woman lays down a book and says, "I'd like to buy this?" Angie rings it up then smiles and says, "Happy what ever you celebrate day" Spec walks up and says, "What did you tell her?" ANgie grins and says, "Why do you want to know?
Did it get you going?" Spec shakes his head and walks off.

Kit returns a minute later as ANgie is finishing up with a customer and says, "Happy what ever you celebrate day" Kit asks, "What was that?" Angie replies< "Was what?" Kit frowns, "What you said" Kit takes back over the registoer and in
her happy tone keeps telling everyone, "Merry Christmas"

Later at home. Kit's laying in bed awhen Angie walks in. Angie is wearing a rob and says, "I got yo usomething" Kit smiels and says, "OK I'll let you have sex" Angie hands her a box and says, "The rob is becuase I just got a shower"

Kit opens teh box and sees a big diamon ring he slooks up and says, "Angie, I " Angie kiss Kit and says, "Happy what ever you celebrate day" Kit frowns Angie takes off the rob revealing a red nightiy then puts on a santa hat and sasy,
"Merry Christmas, Kit"

Kit puts the ring on and says, "It's beautiful" SHe then pulls Angie in and begins feelign ANgie's cleavage that's exposace while Angie puts her hand down Kit's pants to finger her. Their both excited. Angie's happy Kit liked her present
Kit's happy Angie may actually let her decorate and exchange gifts now. but soon their both naked except for ANgie's santa' hat she's still wearing. With on hand their squeezing a breas and the other fingering each other. Their also making
out.

Kit squeezes Angie's nipple and says, "I love the ring" Angie smiels and says, "SHut up" they then go back to fucking. Kit's the first to come but she waits till Angie does before they stop. Kit sighs and says, "I had a good day, Merry 
CHristmas, Angie" Angie smmiles and sasy, "Same to you" They then kiss agian.
