* Chapter 23
** Test results

Kit is laying on the couch her head on Angie's lap. She looks up and says, "Angie why the hell did they bring this show back?" Angie is smiling happily. Angie is laughing and like usual Kit is dosing off. "Why is it the shows that are 
decent get taken off air after three to four seasons but cop shows, reality shows and this aweful crap stays on?" Angie replies, "Kit you don't know what your talking about" Kit looks up and says, "Angie the shwo was rated by every 
critic as the worse show in history. You may be the only person in the world that watches it" Angie shakes her head and says, "If I was they only person the show wouldn't last" Kit looks at her and says, "that order of law show has been 
on air since the early ninties. people stoped wacthing it in ninety six but yet they keep making spin offs like it has a fan base. When in truth not ones wathces it" 

Their conversation is inturrepted by a knock on teh door.

Angie gets up and answer it and sees Charles stnading with a menala enulope. He hands it and says, "They sent the results to my house" 

Angie optns teh envolope and reads it. After a second She hands ti to him and says, "It seems you are my dad" He reads the letter and says, "Can I hug you?" Angie looks up and says, "First no one hugs me. Kit is the only exception" He 
nods and says, "Is this what you wanted?" Angie shrugs and says, "I've thought Tim was my dad for years but suspected he wasn't. Now I know for a fact he isn't. It also makes Jessy my half sister" He frowns and says, "Whay does that
matter?" Angie again shrugs and says, "Feels odd. I just confirmed a suspension. But also makes me wonder how many more sisters and brothers I might have" He laughs and says, "Angie with your", he decides it's best if he dind't say 
anything.

Angie walks over to the couch where Kit is sitting. He helps himself in shuttting the door and locking it. Kit laughs excited and says, "You know your one of the first people to ever lock that door?" He looks puzzled and asks, "Really?"
Angie replies, "Locks are for honest people. The people that want in will come in anyway. Ether threw a window or figure out something. A lock is false security" 

Charles can tell something is eating Angie up and asks, "Angie, I take you where close to this Tim guy?" Angie shrugs and says, "Yes and no, he treated me like a daughter, btu ntohing like take me to the park and sit on his knee. The 
only one that did that ended up taking my virginity" Kit replies, "I thought you lost it years before" Angie shakes her head and says, "No I went into heat. I had a couple of times befroe mom was out. Come to find out with another man.
He walked into my room. I was fingring myself to a picture of the tv star Dinton Star from the show Highton Place" Kit smiles and syas, "He was cute" Angie ignoreing her says, "I looked up and he was jacking off to me. I was ashamed. 
But he sat down beside me on the bed and explained to me it's natural and sex is natural. I'm in heat because my body needs it. He then let me touch his dick. I though it was cool. He then let me jack him off. He then asked if I'd like 
to tast it and he showed me how to give him head. We started fooling around the rest of the week. He had figured out my mom was cheating on him, and using him as a free baby sitter for me and my sister. But a week after we started 
fooling around he asked me if my mom had given me the talk. She had but it was with the assistance of a porno. Next thing I know we where french kissing and then he took my clothes off. I was hesitant but after him asking a couple of 
time I agreed. He got naked. then he asked if we could have sex. We had sex every day after that till mom came home early about a month later. She walked in he had just go tthrew cumming on my face I looked and saw her pissed. We 
where still naked. They screamed at each other till she threw him out. She then left."

Angie shrugs and says, "Well there Kit you found out" Kit looks at her puzzled and says, "Sorry Kit taht's terrible that you where melested and raped like that but" Angie interrupts her and says, "Kit he never raped me. He actually 
told me anytime. I wanted to just say stop. I did once because I was sick he put his pants on and got me some soup. Other times he would sotp and ask what I wanted to do. If it was watch tv he would and a show I wanted and never touched
me" Kit, replies "Angie, the man still took advantage of you" Charles replies, "Angie what ever happened to the man?" Angie shrugs and syas, "I have no idea. I never saw him again" Charles sighs and says, "Angie, I'm sad to say but I'm
shocked your mom was mad at him. It makes me think there is a little bit of hope" Angie looks at him adn says, "She told me a month later wehn I asked about him. She said she wasn't mad that he was fucking me. She was mad becasue he 
cheated on her" Charles shakes his head and says, "Angie, I'm sorry if this makes you mad but I need to say it. Your mom is a worthless bitch" He stands up to leave. But Angie watching tv says, "Why would I be mad over the truth. I
practly raised myself" He looks back and sees Kit mesmorized with the TV he looks and sees a large beuilindg with a sign, "Stardust" with stars on it's side. The news anchor says, "The popular night club Stardust is being closed down
for good because the owner has been arested for murder" She keep talking Charles looks at ANgie and says, "Angie isn't that your club?" Angie nods and says, "Yep" THe news anchor syas, "Misty Beaton has been sentenced to four life 
senteances for first degree murder" Angie laughs and Charles says, "Why are you happy. Ain't you scared?" She looks at him adn says, "I'll figure something out" He frowns and says, "Angie, if you need work. You can also come to my place"

Angie stands up and says, "Chalres, I have a large amount in saveings I'm probably going later this week or next and apply for a loan to open my own place" Charles looks at the floor and says, "Angie I ain't been there for you. So how 
about I lay some money down so you can keep some of your saving?" Angie thinks about it for a second. Befroe saying, "I'm sorry I'll pass" He sighs and says, "Angie, I really want to help you. I'd really love for you to wrok at my place
Hell I woudln't even be your boss. Just charge my prices" Angie laughs and says, "I'd rather have my own place" Charles replies with a smile, "Your like me so please let me invest some money into it" Angie looks at him and says, "I have
another person who's out of work I'm sure would want to" Charles replies, "Angie, I'm going to be a minority holder I won't even have a say in how your place is ran I just want to help" 

Angie finally caves and says, "OK let me sit on it for a few days. Before I call Beth when I'm done I'll call you" He nods and says, "Agreed, I'll be waiting for the investor's meeting"
** Mike
/Mike defends a blond fox from muggers and starts dating her after taking her to a late night cafe that stays open if poeple are in it. they don't chase people off just don't take new customers/

** Jsoh
/Josh talks to Sarah over video chat. and convenses her to come to the city. Where he says, Myabe she coldu help Kit at the book store. but don't know if her boss (spec) will hire her./
