* Chapter 23
** Test results

   Kit is laying on the couch her head on Angie's lap. She looks up and says, "Angie why the hell did they bring this show back?" Angie is smiling happily. Angie is laughing and like usual Kit is dosing off. "Why is it the shows that are 
decent get taken off air after three to four seasons but cop shows, reality shows and this aweful crap stays on?" Angie replies, "Kit you don't know what your talking about" Kit looks up and says, "Angie the shwo was rated by every 
critic as the worse show in history. You may be the only person in the world that watches it" Angie shakes her head and says, "If I was they only person the show wouldn't last" Kit looks at her and says, "that order of law show has been 
on air since the early ninties. people stoped wacthing it in ninety six but yet they keep making spin offs like it has a fan base. When in truth not ones wathces it" 

   Their conversation is inturrepted by a knock on teh door.

   Angie gets up and answer it and sees Charles stnading with a menala enulope. He hands it and says, "They sent the results to my house" 

   Angie optns teh envolope and reads it. After a second She hands ti to him and says, "It seems you are my dad" He reads the letter and says, "Can I hug you?" Angie looks up and says, "First no one hugs me. Kit is the only exception" He 
nods and says, "Is this what you wanted?" Angie shrugs and says, "I've thought Tim was my dad for years but suspected he wasn't. Now I know for a fact he isn't. It also makes Jessy my half sister" He frowns and says, "Whay does that
matter?" Angie again shrugs and says, "Feels odd. I just confirmed a suspension. But also makes me wonder how many more sisters and brothers I might have" He laughs and says, "Angie with your", he decides it's best if he dind't say 
anything.

   Angie walks over to the couch where Kit is sitting. He helps himself in shuttting the door and locking it. Kit laughs excited and says, "You know your one of the first people to ever lock that door?" He looks puzzled and asks, "Really?"
Angie replies, "Locks are for honest people. The people that want in will come in anyway. Ether threw a window or figure out something. A lock is false security" 

   Charles can tell something is eating Angie up and asks, "Angie, I take you where close to this Tim guy?" Angie shrugs and says, "Yes and no, he treated me like a daughter, btu ntohing like take me to the park and sit on his knee. The 
only one that did that ended up taking my virginity" Kit replies, "I thought you lost it years before" Angie shakes her head and says, "No I went into heat. I had a couple of times befroe mom was out. Come to find out with another man.
He walked into my room. I was fingring myself to a picture of the tv star Dinton Star from the show Highton Place" Kit smiles and syas, "He was cute" Angie ignoreing her says, "I looked up and he was jacking off to me. I was ashamed. 
But he sat down beside me on the bed and explained to me it's natural and sex is natural. I'm in heat because my body needs it. He then let me touch his dick. I though it was cool. He then let me jack him off. He then asked if I'd like 
to tast it and he showed me how to give him head. We started fooling around the rest of the week. He had figured out my mom was cheating on him, and using him as a free baby sitter for me and my sister. But a week after we started 
fooling around he asked me if my mom had given me the talk. She had but it was with the assistance of a porno. Next thing I know we where french kissing and then he took my clothes off. I was hesitant but after him asking a couple of 
time I agreed. He got naked. then he asked if we could have sex. We had sex every day after that till mom came home early about a month later. She walked in he had just go tthrew cumming on my face I looked and saw her pissed. We 
where still naked. They screamed at each other till she threw him out. She then left."

   Angie shrugs and says, "Well there Kit you found out" Kit looks at her puzzled and says, "Sorry Kit taht's terrible that you where melested and raped like that but" Angie interrupts her and says, "Kit he never raped me. He actually 
told me anytime. I wanted to just say stop. I did once because I was sick he put his pants on and got me some soup. Other times he would sotp and ask what I wanted to do. If it was watch tv he would and a show I wanted and never touched
me" Kit, replies "Angie, the man still took advantage of you" Charles replies, "Angie what ever happened to the man?" Angie shrugs and syas, "I have no idea. I never saw him again" Charles sighs and says, "Angie, I'm sad to say but I'm
shocked your mom was mad at him. It makes me think there is a little bit of hope" Angie looks at him adn says, "She told me a month later wehn I asked about him. She said she wasn't mad that he was fucking me. She was mad becasue he 
cheated on her" Charles shakes his head and says, "Angie, I'm sorry if this makes you mad but I need to say it. Your mom is a worthless bitch" He stands up to leave. But Angie watching tv says, "Why would I be mad over the truth. I
practly raised myself" He looks back and sees Kit mesmorized with the TV he looks and sees a large beuilindg with a sign, "Stardust" with stars on it's side. The news anchor says, "The popular night club Stardust is being closed down
for good because the owner has been arested for murder" She keep talking Charles looks at ANgie and says, "Angie isn't that your club?" Angie nods and says, "Yep" THe news anchor syas, "Misty Beaton has been sentenced to four life 
senteances for first degree murder" Angie laughs and Charles says, "Why are you happy. Ain't you scared?" She looks at him adn says, "I'll figure something out" He frowns and says, "Angie, if you need work. You can also come to my place"

   Angie stands up and says, "Chalres, I have a large amount in saveings I'm probably going later this week or next and apply for a loan to open my own place" Charles looks at the floor and says, "Angie I ain't been there for you. So how 
about I lay some money down so you can keep some of your saving?" Angie thinks about it for a second. Befroe saying, "I'm sorry I'll pass" He sighs and says, "Angie, I really want to help you. I'd really love for you to wrok at my place
Hell I woudln't even be your boss. Just charge my prices" Angie laughs and says, "I'd rather have my own place" Charles replies with a smile, "Your like me so please let me invest some money into it" Angie looks at him and says, "I have
another person who's out of work I'm sure would want to" Charles replies, "Angie, I'm going to be a minority holder I won't even have a say in how your place is ran I just want to help" 

   Angie finally caves and says, "OK let me sit on it for a few days. Before I call Beth when I'm done I'll call you" He nods and says, "Agreed, I'll be waiting for the investor's meeting" Kit looks confused and says, "Investors meeting"
Angie replies, "It's where you bring in all the poeple intrested in investing in your company. Treat them to a very nice restraunt in hopes of loosening thier wallets to give you more moeny"

** Mike
   Mike is taking a walk. He's feeling pretty content with himself. He just got threw screwing two people at once. He's looking at the redening fall sky when he hears a scream.

   It's followed by another. He looks around and sees a blaond fox with light cherry blond hair being pushed by two men. They're wolves then one grabs her and lifts up her skirt laughing. HS'es kicking at him screaming, "NO" The other one is
pulling at her purse. 

   MIke runs over to them and shoves the one messing with her skirt. The other lets her go and reaches in his pocket pulling out a knife. With a flick of a finger the blade opens. The other says, "Bad mistake buddy" He then pulls out a knife.
Mike's hearts racing but a feeling deap inside of him that he forgot about reemerges. The one on this right lundges for him. Saying, "I'll slash you" Mike grabs his arm and slings him into the other guy. They both fall to the ground but the
other one gets up and runs off. The attacker is laying holding his back screaming. 

   The fox says, "I just got mugged", pauses, "Yes I'm fine thinks to a brave man", pauses, "THank you please hurry we have one on the ground looks like he's bleeding"

   Mike stands over top the man. Until the police and a ambulance araive. The officer asks some questions while the attacker is screaming, "He's going to rpess charges." The officer laughs and says, "Sir next time just call the cops" Mike
replies, "If I had she owuld of been raped and robbed. So I took it in my hands" The officer replies, "What if you where hurt" Mike shrugs and syas, "I'd die knowing I did something" The cop shakes his head and says, "Well we ahve no 
reason to press charges on you. THe man that you said attacked you Got stabbed in his back by his partner" He then walks back to his car

   Mike looks at the fox and says, "Are you ok" She nods shyly and says, "Yes". Mike sighs and says, "Good, Im'm Mike" She smiles and says, "You can call me Ashley" He nods and says, "I know it's late but would you like to get some coffee to 
settle your nerves?" She smiles and says, "I think coffee is the last thing I need to settle my nerves but I would like some teea if it waould b ok" He nods and says, "Do you know a place?" She nods and syas, "There is a little coffee book
store at the corner"

   They walk over to it the waitress sits them at a corner table. Mike says, "Are you about to close? So we can get it to go if you are" the waitress Smiles and says, "No take your time. We close the doors at ten but if your already in here 
we stay open till your done. Mike nods and says, "WE won't be long" the waitress smiles again and syas, "I don't want to rush a date take your time. your giving me over time and I need it" Mike laughs and syas, "OK glad I can help" Mike 
orders a pumpkin spice coffee and Ashley orders a sweet tea.

   Ashley smiles and says, "Thank yo for helping me. I wish I could pay you back" Mike shakes his head and syas, "No please. You reminded me of myself. I kind of been acting diferently lately." She's confused but smiles and says, "OK " 

   They talk for a bit before Mike says, "We've been here for about a hour. WOuld you like to go out on a official date sometime?" She smiles and says, "I'l find a baby sitter" Mike doesn't cough though he is shocked. But don't show it. 
Instead he sasy, "OK" She shakes her head and syas, "Your ok if I had kids" Mike shrugs and says, "I like kids. All I ask is if I can meet them" She smiles and says, "I don't have any but I'm glad to know you'd b ok if I did"

   He looks up to the waitress and sees her reading a jelwerly magazine with a smile circling stuff. He laughs and throws a five on the table boefre walking Ahsley out.

   Outside he asks her, "So would you like me to wlak you home?" She takes his hand and says, "Yes, please" They walks up to a light grey square building. At the font is a glass double door. It's only the olny sign this isn't a abandoned
buidling. She smiles and says, "Two hundred a month rent" He walks her up to the second of four floors. They stand in front of the door and he says, "Well thanks for leting me take you" She smiles and replies, "Thanks for the tea" She
hands him a peice of paper and says, "I'm sure yo uwant my nubmer" He nods and says, "I'll call you when I get home" She smiles and syas, "htat would be nice"

   Next thing he nows his on his way home with his hands in his pockets
** Josh
   Josh is laying on his bed video chatting with Sarah. HE smiles at her and says, "It's not to finally siee you. She loks down and says, "Everyone says, "I look like my sisters" He shrugs and says, "No your prettier" Sarah has hear hair
back ina pony tail tied back witha  blue ribbon. She is also the only sister that has to wear glasses. 

   Josh smiles and says, "So what do you do?" Sarah shrugs and says< "Not really alot to do in the holler. So I mostly just stay home. Kit was the lucky one she got out" Josh shrugs and says, "Why don't you leave?" She shakes her head and 
says, "No I coudln't I mean I'm needed here" JOsh frowns and says,"How are you needed you just got threw saying there is nothing to do" She growns and says, "If I did move there. I wouldn't have anything to do. I can't just live there
and freeload" Josh replies, "Maybe Kit cuold talk to her boss and get a job there at the book store where her and Angie work" She shrugs and says, "I'm not much of a bookworm" Josh smiles and says, "And Angie is?" Sarah laughs and says, 
"Good point . But she is really smart" Josh frowns and says, "She also thanks every man has a crush on her" Sarah replies, "Well? Do you?" Josh shakes his head and says, "yes she's cute but I'm just not intrested in whores" Sarah smiles
and says, "Well It's geting late" Josh smiels and says, "Yeah, but I really wish you'd think about moving here" Sarah shrugs and says, "I can't" Josh asks, "OK why can't you?" She shrugs and says, "I really don't have a reason", giving 
up. She sighs and says, "I promiss I'll think about it. I can't guarentee anything but I'll think about it" Josh smiles and sasy, "thank you . Talk tomarow" She nods and says, "Good night" He says the same befroe waiting to turn off his 
tablet.

   He looks up in his door way and sees Kit standing there puzzled. She's wearing a pink night gown and says, "Who was you talking to?" Josh shrugs and says, "Some girl I've been talking to" Kit lights up and says, "Oh who would that be?"
Josh shrugs and says, "Just a girl" She sits down on his bed with her knee up and says, "So your seeing a girl and don't know her name" Josh has his head turned and says, "Kit please I can see everything" Kit puzzled asks, "What?" Josh
replies, "YOur not wearing underwear"

   She quilcky sits up and says, "Oh shit I'm sorry" She's embarrsed and says, "I just thought we use to fuck and haven't in a while" Josh frowns and sasy, "I"ve been the third wheel now since we've moved into this place, and you never once
came in here. Now I'm talking to osmoene you want me?" Kit shrugs and says, "I" Josh stops her and says, "Kit what where you really going to do? And remember I know you fuck Mike" Kit shrugs and says, "Mike wasn't in his room. Chase is 
watching TV" Josh replies, "Oh so I was your last choice?" Kit looks down and says, "Sorry, I'm just horny. Everything is changing" josh frowns adn says, "Yeah I hate change to and I take you do also?" She nods and says, "So who where you
tlaking to?", with a big smile. Josh shakes his head and says, "Kit, go to bed" Kit nods and says, "Sorry", she then leaves.

   Josh lays down on his bed and says, "I waited on her for almost a year to come back to me. As soon as I start tlaking to someone she comes running.
