* Chapter 23
** Test results

Kit is laying on the couch her head on Angie's lap. She looks up and says, "Angie why the hell did they bring this show back?" Angie is smiling happily. Angie is laughing and like usual Kit is dosing off. "Why is it the shows that are 
decent get taken off air after three to four seasons but cop shows, reality shows and this aweful crap stays on?" Angie replies, "Kit you don't know what your talking about" Kit looks up and says, "Angie the shwo was rated by every 
critic as the worse show in history. You may be the only person in the world that watches it" Angie shakes her head and says, "If I was they only person the show wouldn't last" Kit looks at her and says, "that order of law show has been 
on air since the early ninties. people stoped wacthing it in ninety six but yet they keep making spin offs like it has a fan base. When in truth not ones wathces it" 

Their conversation is inturrepted by a knock on teh door.

Angie gets up and answer it and sees Charles stnading with a menala enulope. He hands it and says, "They sent the results to my house" 

Angie optns teh envolope and reads it. After a second She hands ti to him and says, "It seems you are my dad" He reads the letter and says, "Can I hug you?" Angie looks up and says, "First no one hugs me. Kit is the only exception"

** Mike
/Mike defends a blond fox from muggers and starts dating her after taking her to a late night cafe that stays open if poeple are in it. they don't chase people off just don't take new customers/

** Jsoh
/Josh talks to Sarah over video chat. and convenses her to come to the city. Where he says, Myabe she coldu help Kit at the book store. but don't know if her boss (spec) will hire her./
