* Chapter 24
** Mike and Chase
Mike sits down on Chase's bed. Chase who's on a tablet playing solitare says, "Mike please knock" Mike replies, "Chase ,plaese lock your door" Chase puts the tablet down and says, "Mike this is my room why do you walk in?" Mike shrugs and
says, "Chase this time I came in to apologize. Here lately I've been acting weird ever since I found out I liked men. Well I did have sex with a man" Chase picks up the tablet and says, "Yes next time tell them not to come in my room 
asking if I'll join" Mike nods and says, "There won't be a next time. I just wanted to tell you first I'm OK" Chase shrugs. Mike continues, "I took a walk a minute ago filling good at myself for doing something I've wnated to whin I saw a 
cute fox geting muged. I'm proud to admit I helped her and ended up geting a date" Chase nods and says, "Cool. Now can I get back to my game? I almost won" He shows him the solitare game. Before starting back.

Mike gets frustrated and says, "Chase, I did osmething good today" Chase sits up frustrated and says, "Yes you did. But every time I help soemeno on the side of the road change a tire or give them a jump. I don't go in your room bugging
you. Mike says, "I just thought you'd like to know how your big brother did it" 

Chase reples, "Mike, why whould I care?" Mike replies, " Because one pulled  aknife on me and I stoped him. He ended up geting stabbed by his partner who I didn't see had also pulled a nkife on me" Chase nods and says, "Mike I'm sorry I'm
not excited but I'm trying to get over Cinthia" Mike is puzzled and says, "Who's that?" "You know what whore at work? That bugs us all the time?" Mike nods and says, "Chase what did you do?" Chase sighs and says, "I don't know how it 
happened. I was carring a bunch of boards went I got a back spasm. I fell on the floor and well she is a nurse so she insisted on looking at it. None of the guys would help they where to busy and didn't notice I went down" Mike shakes his
head and says, "Chase did you file a accedent report?" Chase shrugs and says, "Cinthia messaged the cramp out. Then I don't know what ahppened but we wore in my truck and she was giving me head" Mike covers his face and says, "Chase your 
the sane one of the family" Chase sighs and says, "Well she kept going until lunch when I took her into the trailer and fucked her" 

Mike stands up ands ays, "Just so you know. The last guy that did her got fired" Chase nods and says, "That's why I"m worried" Mike says, "I'll call Bob" Chase replies, "Don't he didn't say anything after lunch. He didn't act any diferent"
Mike replies, "Trust me he knows what you did" 

Mike wlaks in the hall and calls Bob, their foreman. He answres right off. ANd says, "Mike I take your calling me about Chase's fling with that fox" Mike replies, "I thought you'd known" Bob replies, "Yeah she druged him" Mike is shocked and
says, "And why are you just now saying something?" Bob replies, "Because we don't knwo how she did" Mike takes the chance to say, "Well for one why didn't anyone help him" He says, "Because he just stoped and held his back then layed the 
boards dwon and disappeared" Mike now confused, "Does he need to get to the hospital?" Bob replies, "I don't know but he passed out in his truck till  after lunch hwne he freaked out thinking he droped the boards" 

Mike wlaks back into the room adn says, "Chase Bob thinks you where durged" Chase laughs and says, "Why's that" "Because he said you passed out in your truck"  

Just then his phone rings. On the other end is a man lauhging hard. Chase replies, "Dan what did you do?" "Oh man that was great. I sliped three sleeping pills in your coffee when you whasn't looking. And the greatest thing is they think
that that slutty fox did it" Chase is mad and hangs up on him.

** Angie's proposition

Angie tells Beth, "Well I just got a phone call from mom. If it's still ok. Jessy can move back in" Beth happily replies, "Oh that's great. I'm glad her mom changed her mind" Angie lauhgs, "Mom didn't relaly change her mind as backed into
a corner" Beth giggles. Then Angie says, "Beth I know your usually a little cheerful but tonight your more. Did you get a new job already?" "No. It's just me and Vicky has been talking and she agreed to something" 

Angie says, "OK .... Well I've been thinking of something myself" She pauses, she's been runing it threw her head and thinks it may be to early stil but says, "I recently discovered my biological father" Beth replies, cheerfully, "Oh 
that's great Angie congraduations" Angie says, "Yeah yeah yeah. and all that stuff but he gave me a idea with out meaning to. How about you help me open a small place. Nothing big. No strip club or anything. Just mostly A day shift worker
then a night guy with some people. Then when one of use or both come in they can go help us" 

Beth says, "It's better than my idea but your willing to down size?" "Beth, the Den failed because it was to big and to pay the bill had to be a front for illegal activity. Stardust same thing. This place will be small. Hell a day job 
might beable to keep it open. It'll be alot easier to manage. Saving money on security. We won't basicly need out own minipolice department to keep it safe. A few security guards and bouncers will be sufficient"

Beth says, "So how many people are in on this?' Angie replies, "So far just me and you. And the greatest thing. You can still be Vicky's boss she can keep working there. except she'll be working for me also. But I might be able to talk
Kit into joining. I still have to work out alot of kinks in it but if your up to it" Beth chearfully says, "This is great. Can I still do my practice like I did at the last. I helped alot of people out" Angie knows she did one guy came in
for his last drink he was going to lay on the rail road tracks and end it but Beth talked him into getting help then leaving his problem which was a cheating wife. There was a bunch of other people just not as dramatic" Angie says, "Great
if you want to help me prepare a investors meeting since you've had a little experance in meetings" Beth confused asks, "Huh?", in her chearful voice. Angie laughs and says, "Your a doctor Beth don't y'all have meeetings and shit?" Beth
replies "Yeah... but those ain't investor meetings. But I do have a friend that went to college for business" Angie agrees then they hang up.

** Kit
Kit sits on Angie's bed and asks, "I'm sorry I over heard your conversation" Angie says, "We're just throwing idea out right now. It porbably will be a complete diferent idea expecially after we have a meeting and the people who want to
invest put thier ideas in. Then we'll get some  designers to look over and will talk to banks. But it feels weird going the legal route" Kit replies, "Angie, Misty tried this route originially didn't she?" Angie replise, "Yes but Misty 
had substained a bunch of debt. She dind't have any real investors except us. She gave us our own bars. SImpley went to big to fast. Me and Beth, are starting small then grow as neded" Kit cautiusly says, "How much do you have to pay to b
be a investor?" Angie smiles and says, "Kit if your wnating to be part of this. you already are. But no one has made a offer yet.

Kit then smiles and says, "I need to get to bed.  I have to be at work tomaorw" Angie shrugs and says, "So do I" Kit replies, "Won't you sleep with me?" Angie smiles and says, "OH? and why would I wnat to?" Kit smiles and lisft up her 
shirt showing a lacy black bra then going to her room"
