* Chapter 25
** Kit
Kit wakes up stretching she smiles thinking of the night before remembering. The night before after Kit showed Angie her bra she started taking off her clothes Kit followed suit. Angie smiled at her panties and said, "Nice your underwear 
matches" 

Kit quickly takes them off and her and Angie where laying in bed making out. Angie gave Kit a few smacks on her firm ass before beginning to finger her, and squeezing her laughs breast. Kit enjoyed the fingering while making out and 
squeezing Angie's breast.

Kit cumed three times and Angie two before they both went to bed naked.

Now Kit looks at the door and says, "Hey Angie we got work" Angie sits up and says, "I miss sleeping in" Then gets dressed. She stops and says, "Who shut the door? Kit shrugs and says, "Thought you did" Angie is putting her pink bra on
and says, "I thought you did" Kit gets dressed puzzled. She goes into her closet and gets out something suitable for work.

Angie laughs and says, "Why do you wear the same type of clothes? We both know Spec has the hots for you. You don't even have to try" Kit shrugs and says, "First it's been almost a month since we did anything. Second we have customers
that don't want to see a fox dressed in skimpy clothes" Angie smiles and says, "I sold three books just the other day" Kit growls and yells, "IT'S A BOOK STORE! PEOPLE COME TO YOU TO BUY BOOKS" Angie grabs her keys then leaves, saying,
"Keep telling yourself that" Kit walks up and "Angie", smacks her ass hard and says, "Get some regular clothes on" Angie turns and says, "KIT!" Kit is pointing to Angie's room. Angie looks down frustrated and says, "Kit" Kit stops her and
says, "Angie seriously even you said the man has no interest you in, and right now this is your only way to get a paychecks" Angie takes a deep breath and says, "Kit be careful" "Angie, seriously please" Angie, shakes her head and leaves and
says, "I  know someone who's walking today", leaving Kit standing.

** Work
  Kit walks in tired then goes and puts her stuff up. Angie follows and asks, "So have a nice walk?" Kit replies, "Go to hell, Angie" Spec don't look up from his newspaper.

  After the door closes Kit yells, "WHAT THE HELL!" Angie frowns and says, "Kit your being a bitch. I agreed to let you to teach me manners. But this is going to far. Ether you like how I am or not. I'm not going to change. I'll break up 
with you way before that" Kit is frowning and says, "We'll talk later" she then goes out and begins work.

  At lunch Angie walks into a sandwich place she went a few months before. The person taking the orders is a young badger probably late teens. Angie smiles at her chest. Which is a little bigger than Kit. The badger says, "I heard you like
to pay in other forms" Angie smiles and says, "I'll have the spicy chicken club with extra fries" The badger smiles and says, "I just cleaned the bathrooms" 

  Angie stand up straight and says, "What?" The badger rolls her eyes and says, "I how you paid last time. I don't mind buying your meal for that" Angie hears Kit calling her a whore. She looks down and says, "I think it was someone else" 
The badger grins and says, "No they gave a clear description and said, "That's the first time they hired a whore" Angie's mouth drops she then says, "What did you just call me?" The badger smiles and says, "So it was you" Angie slaps her 
hard and says, "Shut up" 

  Just then Angie hears, "What the hell did I see you do? I'm calling the cops" Angie defends herself by, "This woman was harassing me calling me a whore" The server shakes her head and says, "Jonny I swear she just asked me to lean in and
then she hit me" The manager replies, "Mam I'm going to have to ask you to leave and don't come back" Angie looks at him and said, "Your not even going to check the cameras? This please is really a shitty restaurant and trust me. People 
will hear about it"

  She then turns and says, "OK mam, I'll play along just if she was serving you the proper way. I'm not going to let you go. I'm pressing charges" Angie shrugs and says, "What ever makes you happy"

  Fifteen minutes later. He returns and says, "Jessica to my office now" The badger says, "But she hit me" Jonny walks up to her and quietly says, "After you where clearly hitting on that woman" Jessica says, "I can't believe this. This is
because I didn't fuck you ain't it? Oh my God" She then shakes her Head says, "I saw you staring at my ass" Jonny sighs and says, "File a complaint but I never did that stuff. Your fired" Jessica starts crying and says, "Oh God this
is illegal. I'm suing" She then runs out crying

  He walks up to Angie and says, "Order what ever you'd like it's on the house" Angie shakes her head and says, "No I'd like to see you reprimanded" He blinks and says, "I had" Angie interrupts and says, "No customers are always right. Your
 suppose to assume I'm right then go and prove it. Or take a neutral role, and check it out" Jonny nods and says, "Mam I understand" He then nods and says, "One minute"

  A few minutes later after feeling out a paper and says< "There I wrote myself up" Angie nods and says, "now shred it and I'll have a spicy chicken sandwich and potato wedges to go" He nods and says, "OK mam" 

  After Angie takes her stuff and is going out the door. She hears him say, "Fucking whore" Angie turns around but the man runs out of site. Angie growls and goes back to work, "Place stinks anyway"

  Angie throws the empty bag in the trash and looks up to Spec saying, "Sorry I'm late I had a little situation at the restraint" She then goes and finds Kit. Where she just says, "Kit we need to talk at home" Kit still mad says, "We've
already established that"

** Beth

Beth is sitting rolling a small ball on the coffee table back and forth. When Vicky sits down beside her. "Something wrong?" Beth looks at Vicky with a smile, "Me and Angie has been talking. It seems me and Angie might be going back in 
business soon" Vicky smiles and says, "Oh what's this place going to be" Beth repositions herself and says, "Oh so what's this place going to be? It is going to have a pond in the center so people can go skinny dipping?" Beth gets the 
sarcasm and replies, "No this place will jsut be a pub I think or a lounge" Vicky laughs and says, "SO Angie is thinking small. I guess hell has frozen over" 

Beth smiles nodding and says, "But we're going to have a investors meeting to see who's intrested. Aslo", she points ot the couch, "Jessy's home" Vicky looks over to see Jessy on her phone with her ear buds in.

Vicky looks at Beth and asks, "Does Angie know?" Beth nods and says, "Yes actually there mom consided" Vicky nods, "Well back to the businesss idae. How much experiance do y'all have?" Beth shrugs and says, "I'm a doctor and she's I'm not
sure what she is" Vicky laughs and says, "Yeah a doctor and a slut. Tha'ts going to be a successful business" 

Beth straightends up adn says, "Actually Vicky I've been wanting to ask. I sort of have someone who can help but one problem"  Vicky waits for her. Beth after a minute sasy, "It's my exgirl firend" Vicky shrugs and says, "WHich one?" Then
Vicky picks up on her nervousness and asks, "Beth, what is going on? I know you've fucked other girls" Beth sighs and syas, "It's my exboyfriend" Vicky alughss and sasy, "Beth I've had boyfriends to" Breth replies, "But I'm gay Vicky"

Vicky frowns and says, "Call him Beth" Beth nods and says, "OK. I hope he can get over the break up. It didn't really go good" "OH? what happened?" Beth scratches her neck, "Well. We where on a date and had this really cute watress. I mean 
she was hot. She started flurting with him but he didn't have anything do to with it. Then on the way home he made a joke and asked how I felt about it. I hsruged and smiled" A few weeks down teh road we went abck and it ahppened again.
This time he pointed and said, "I'm with her actually" she appologized and I got nervous wehn she said, 'Oh honey I am sorry I  should of known he was dating such a cute kitty' She smiles and walked I giggled and he looked at me wierd. We
did talk until he was taking me home. Where he was direct and asked if I was bi. I deniged it. He seemed to know somehting I didn't because he never really let it go. He was constantly asking if I though girls where cute. Sometimes I did
toher's I didn't but was still denighing it. Finally after him asking me so much it got me thinking so I went to a gay bar. I wasn't planning for anything to happen. But the next day when he came over and knocked on my door. Well I was 
really hung over but looked over and saw I was naked in bed with another woman. We got dressed and ran out. She blew me and kiss and said she dind't mine playing my game. E came in and said sorry about constantly asking about girls that 
he would quit but he saw a bra on the floor. It was hers. She had a pretty decent size chest so there was no saying it was mine. He adomatitly said, 'My god you are a dike' We yelled at each other for a bit. He got mad and left."

"a couple of days later he showed up drunk with a girl who was also drunk. He kissed me and said he had us a girlfriend. I looked and she said, 'I fuck anything' I had a surge of rage. I slapped him and she said, 'Oh bondage I love it'. 
He made a comment about it to so I kicked him in the crotch and threw them out. He showed up again a few days later with another girl. That time I didn't even give him time to talk. I screamed at him to take his whore home. Then I broke up
with him. He still tried a few times with other girls. I screamd that we are broke up. He then shwoed up with a girl. But this time I had my first girlfriend" Beth blushes, "The watress I first noticed. We dated for a few months before
breaking up. He still tried to date me but said he's share"

Vicky is confused and said, "Why do you want to call this man? Sounds like he was a realy thorn in your side"

Beth rolls her eyes, "I know he won't bother me now. The waitress I dated. Left me for him. Their married now and have two kids. And yes from what I know she brings in girls and has three ways with him. But he's also a business advisor for
a big investment firm that sirves small bisineses"

Vicky nods and says, "Actually since you seem to still be atracted to him" Beth frowns, "Still hate him" Vicky smiels and says, "You glow when you talk about him" 
"Do not"
Vicky giggles and says, "Since his wife is ok with . How about he makes us both bregnant"
"NO! NO! Ihave someone set up actually he's just wiating but no not Sid. It's a ass and would b back in my lief and I finally got rid of the creep" Vicky kisses her and says, "OK, But more about this man" 
Beth smiles big and replies, "More about him later"
